commodore/compile.py
commodore/target.py

Add the cluster catalog repository URL in the Kapitan cluster target
file as parameters.cluster.catalog_repo. Note that this value will most
likely be in the format ssh://git@example.com/path/to/repo which is
Commodore's normalized repository URL format.
Signed-off-by: Simon Gerber <simon.gerber@vshn.ch>

Add cluster catalog repository in Kapitan target file

---

docs/modules/ROOT/pages/writing-a-component.adoc

Add a section which briefly explains the Kapitan class hierarchy for
component writers.
Signed-off-by: Simon Gerber <simon.gerber@vshn.ch>

Add section on Kapitan class hierarchy in Commodore docs

---

commodore/refs.py

Instead of picking only some of the configuration options, use the whole
dict since the key names are the same anyway.
Signed-off-by: Simon Rüegg <simon.ruegg@vshn.ch>

Configure refs with dict

---

Pipfile.lock
commodore/compile.py
commodore/helpers.py

This allows us to still explicitly check the return code of the call to kapitan in the compile() method. With check mode enabled, subprocess.run raises an exception instead of just returning the return code of the subprocess.

Explicitly disable check mode for subprocess.run in kapitan_compile

---

commodore/config.py
commodore/helpers.py

This commit changes Commodore to optionally read the API token from a
file. If the API token argument (command line or environment variable)
exists as a file, Commodore will read the file contents and use them as
the API token. Otherwise the value of the argument is used as the API
token. This allows using the service account's token when running
Commodore on Kubernetes.
Relates: SYN-21

Allow reading API token from file

---

commodore/config.py

While illegal characters are not a problem for checking whether the
provided API token value is a path, pathlib fails to properly handle
long tokens (e.g. JWT), and fails with the error `OSError: [Errno 36]
File name too long: '...'` when encountering such a file name.
This commit wraps the whole check whether the provided API token value
is a file name in a try-block and silently assumes that any OSError
thrown by pathlib indicates that the provided value is not a file name.

Fix check whether API token is a file

---

.github/workflows/push.yml

The imported Github action for pushing the docker image to DockerHub
does not run the `make docker` command and therefore the Commodore
binary version in the pushed image was not configured correctly.
This commit generates the binary version as a Github action step instead
of relying on the Makefile when building the image to be pushed.

Ensure Commodore binary version is set when pushing image

---

Pipfile.lock
commodore/git.py

This commit changes `git.clone_repository` to create an empty initial
commit when cloning an empty repository.  In particular, this change
removes the need to pre-initialize a new catalog repository outside of
Commodore.
Resolves #59

Create initial commit in cloned repositories if no commits exist

---

Dockerfile
Pipfile
Pipfile.lock
commodore/cluster.py
commodore/compile.py
commodore/component_template.py
commodore/postprocess/__init__.py
commodore/refs.py
requirements.in
requirements.txt

Addresses pylint failures for "W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)".
Additionally also bulk updates dependencies, and fixes the Docker image build

Convert all f-strings without interpolations to regular strings

---

commodore/git.py
tests/test_git.py
tests/test_target.py

Follow up for https://github.com/projectsyn/commodore/pull/88 review

Reformat tests

---

commodore/cluster.py
docs/modules/ROOT/pages/writing-a-component.adoc
tests/test_target.py

Add sub folders `distribution` and `cloud` for the respective classes.
Needs to be merged with:
* https://git.vshn.net/syn/commodore-defaults/-/merge_requests/6

Organize global classes in folders

---

commodore/cluster.py
tests/test_target.py

Relates to https://github.com/projectsyn/lieutenant-api/pull/52

Lieutenant Fact

---

Pipfile
Pipfile.lock
requirements.txt
tools/Dockerfile.kapitan

This includes among other fixes proper Vault error handling [1].
[1] https://github.com/deepmind/kapitan/pull/512
Signed-off-by: Simon Rüegg <simon@rueggs.ch>

Upgrade Kapitan to v0.27.3

---

.gitignore
CHANGELOG.md
README.md
commodore/catalog.py
commodore/compile.py
commodore/component_template.py
commodore/config.py
commodore/dependency_mgmt.py
commodore/git.py
commodore/postprocess/__init__.py
commodore/refs.py
tests/test_compile.py
tests/test_dependency_mgmt.py
tests/test_git.py
tests/test_new-component.py

Allow overwriting of component git repo URLs.
The component git repo URLs can be overwritten in a global Commodore
config file. The config file is searched for in the global inventory
repo. The global git base is used as default for non overwritten
components.
Closes #73

Component URLs

---

commodore/cluster.py
tests/test_target.py

If a fact is set to an empty string, handle it accordingly. Depending if
the fact is required or not, fail or ignore it respectively.

Handle empty facts

---

commodore/catalog.py
commodore/compile.py
commodore/config.py
commodore/dependency_mgmt.py
commodore/git.py
tests/test_git.py

In addition to the version this allows to override the Git URL for a component, using the `component_versions` dict. This allows for example the usecase of a forked component repository to be used for a certain part of the hierarchy.
Closes https://github.com/projectsyn/commodore/issues/73

Allow overriding of component URL in inventory

---

CHANGELOG.md
lib/commodore.libjsonnet

Some environments require the `HTTP_PROXY, `HTTPS_PROXY` and `NO_PROXY`
variables being set. The helper `proxyVars` sets them when needed.

Add helper to get proxy environment variables

---

CHANGELOG.md
commodore/cli.py
commodore/component-template/cookiecutter.json
commodore/component/template.py
tests/test_component_new.py

Sometimes the components slug and the wording in the documentation can not be handled with simple transliteration rules. This PR adds an option to set them differently. This is done by changing the `commodore component new` command to take the slug instead of the name as its argument. In order to set the name again, an option is added.

 Option to explicitly set a component's display name

---

CHANGELOG.md
commodore/catalog.py
tests/test_catalog.py

Remove leading newline from commit messages

---

.github/workflows/test.yml
CHANGELOG.md
tox.mk

The setup-python action does not install multiple Python versions
anymore, but defaults to the latest stable Python 3 version. The version
can be selected by specifying `python-version` to the action.
This commit refactors the testing workflow to setup the right versions
to run the tests under Python 3.6, 3.7, and 3.8.

Refactor test GitHub workflow to ensure right Python version is installed

---

CHANGELOG.md
README.md
commodore/catalog.py
commodore/cli.py
commodore/compile.py
commodore/component/template.py
commodore/config.py
commodore/dependency_mgmt.py
commodore/git.py
docker-compose.yaml
tests/test_git.py

This commit introduces new arguments for `commodore catalog compile` for
overriding local Git user information when pushing commits to a cluster
catalog.
By default Commodore will use the local Git user information for catalog
commits.
To improve compatibility with existing Git configurations, the arguments
are named `--git-author-name` and `--git-author-email` to pick up the
familiar `GIT_AUTHOR_NAME` and `GIT_AUTHOR_EMAIL` environment variables
without any further configuration.
Please note: Commodore does not allow you to override commit author and
committer separately, and will use the provided author name and email,
if any, as both commit author and committer.
The commit also updates docker-compose.yaml to map `~/.gitconfig` into
the container to propagate the global Git config into …

Allow overriding Git user info for catalog commits

---

docker-compose.yaml

Adds host network support to the docker-compose.yaml file, so that Docker-based Commodore can connect to local instances of the Lieutenant API.

Added network requirements in the docker-compose.yaml file

---

CHANGELOG.md
commodore/config.py

Since long tokens might be used which can't be valid file names.

Ignore filename too long error

---

CHANGELOG.md
commodore/cli.py
commodore/component/template.py
tests/test_component_new.py

Prevent components having the `component-` prefix in their slug.
Closes #152

Validate new component slug

---

CHANGELOG.md
commodore/component/compile.py
tests/test_component_compile.py

When compiling a single component using `commodore component compile`, any postprocessing filters which are defined for the component should be applied to the output of `kapitan compile`.
This commit adds code which calls the usual `postprocess.postprocess_components()` method for just the component that is getting compiled.

Run postprocessing filters when compiling a single component

---

.gitignore
README.md

This PR includes folders that were previously ignored. 
The reason is the `docker run projectsyn/commodore catalog compile` command which generates those folders as belonging to the root user, which prevents from writing to them. Situation found on a Ubuntu 18.04 system. The solution was to `mkdir` the folders before running the command.

Add folders generated during catalog compilation

---

CHANGELOG.md
commodore/postprocess/__init__.py
commodore/postprocess/builtin_filters.py
commodore/postprocess/inventory.py
tests/test_postprocess.py

It can be helpful to make postprocessing components optional based on a reclass reference.
This PR implements this feature by introducing an optional field `enabled` for each filter definition. If the field doesn't exist, filters will count as enabled. This feature is particularly useful if we want to apply a filter to a subchart of a Helm chart which can be enabled or disabled, e.g. Postgres for Keycloak.
The PR also introduces a first set of tests for `postprocess_components`.

Allow postprocessing filters to be disabled

---

CHANGELOG.md
Dockerfile
README.md
tools/Dockerfile.build_kapitan_helm_binding
tools/build_kapitan_helm_binding.sh

To be able to use the native Helm dependency type [1].
[1] https://kapitan.dev/external_dependencies/#helm-type
Required for https://github.com/projectsyn/component-cert-manager/pull/2

Build native Helm dependency binding

---

CHANGELOG.md
commodore/compile.py
commodore/dependency_mgmt.py
docs/modules/ROOT/pages/reference/architecture.adoc
poetry.lock
pyproject.toml

One consequence of this is, that the hierarchy can't reference parameters which are defined in component classes (i.e. defaults). This is due to the fact that a reclass inventory must be able to resolve all references in order to be rendered. There's no mechanism to ignore invalid references (like there is for ignoring inexistent class files). 
Closes #138

Component Discovery With Reclass

---

CHANGELOG.md
commodore/catalog.py
commodore/cli.py
commodore/dependency_mgmt.py
docs/modules/ROOT/pages/reference/cli.adoc

This commit adds the "commodore catalog list" command that will query
lieutenant for a list of available cluster IDs (and descriptions), and
display the information on stdout.
This partially helps with #135 
Unit tests have not been added since the logic is trivial (basically printing out contents of an already-existing API) and consists mostly of stiching side-effects. Mocking side-effects (the click library and lieutenant function call) would result it unit testing a for loop, which I suspect is not very interesting.

Add "catalog list" command

---

commodore/cli.py
commodore/component/template.py

This is a simple nitpick branch - Having a class called *Factory makes me assume (and I suspect other programmers as well) that the object is an implementation of the Factory design pattern.
Changing the name of the class avoids this confusion without changing program behavior at all.
Note: this is a nitpick in its purest form - don't feel bad closing this PR without further comment :)

Rename ComponentFactory to ComponentTemplater

---

CHANGELOG.md
docs/modules/ROOT/pages/reference/commands.adoc

The documentation for the `component new` command was rather dense, and required some prior knowledge.

Improve and clarify component new command documentation

---

CHANGELOG.md
commodore/component/template.py
commodore/helpers.py
tests/test_dependency_mgmt.py

Should "component create" be called outside of a catalog, display some
information in this regard to the user.
The lower layer exception (FileNotFound) is not wrapped in the top-layer
click.Exception() wrapper anymore in order to differentiate exception
types.

More explicit error when failing to add component

---

commodore/component/compile.py

This was said out loud while digging through the code with Simon, the
information as to why we fake argoCD might be interesting to future
travelers.
This is a trivial PR (no functional changes whatsoever)

Tiny comment addition

---

.github/workflows/test.yml
CHANGELOG.md
commodore/config.py
commodore/helpers.py
tox.ini
tox.mk

This commit adds a tox mypy validation test environment, and makes a few
simple adjustments to ensure the current code passes said validation.
This PR adds some testing to the project (static analysis for optional types).

Add mypy validation step to tox

---

CHANGELOG.md
tox.ini

The bandit version used by this project was pinned to pre-1.6.0 which
seems to fail silently (!) locally and on CI.
Running `tox -e bandit` before this commit:
https://pastebin.ubuntu.com/p/V72Q49XvTt/
After this commit:
https://pastebin.ubuntu.com/p/82S9XTCqW9/

Fix bandit

---

CHANGELOG.md
commodore/component/template.py
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_component_new.py

In https://github.com/projectsyn/commodore/pull/186 we decided to disallow component slugs with a leading digit. While implementing this policy, I've suggested to restrict slugs further.
After some further discussion, we decided to restrict component slugs to the regex `^[a-z][a-z0-9-]+[a-z0-9]$`, when creating components with `component new`.
This PR implements slug validation in the component templater using the regex mentioned above, and introduces a number of test cases which validate the new behavior.

Implement slug validation for `component new`

---

commodore/component/compile.py
tests/test_cli.py
tests/test_component_compile.py
tests/test_dependency_mgmt.py
tests/test_target.py

This branch provides two nitpicky non-functional changes:
1. Switch from using os.system() to the higher-level subprocess.call() (the recommended interface for shelling out in python). In particular this allows to retrieve non-zero exit codes instead of getting the syscall + exit code integer from os.system.
2. Use textwrap.dedent() to have the yaml snippets aligh with the rest of the code instead of "leaking" to the left-hand side of the text file.
These changes are entirely "cosmetic" and should not affect the functionality at all.

Subprocess changes and dedent

---

docker-compose.yaml

The use of distinct volume mounts for each and every directory does not
scale. Whenever something new is added, the docker-compose config would
need to change. Instead, we can use only one volume by also changing the
workdir within the container.
This change got triggered by #196.

Simplify docker-compose configuration

---

Dockerfile

Having Poetry installed within the same scope as the application, can
result in unexpected behaviour. Using their install script, puts poetry
in isolation and no interference should occur.

Do not use `pip` to install Poetry

---

CHANGELOG.md
docs/modules/ROOT/pages/reference/hierarchy.adoc

There were a few places in the hierarchy documentation which referred to `common.yml` in the global config repository.
Since Commodore now uses `global.commodore` as the hierarchy starting point, the documentation should refer to `commodore.yml`.

Replace remaining references to common.yml with commodore.yml

---

CHANGELOG.md
commodore/helpers.py

Kapitan 0.29.3 contains  [PR#625] where the default inventory path `./inventory` is removed and the default path is extracted from the command line argument if necessary.
Since we do not call Kapitan via the CLI we need to manually populate the argument cache.
This commit introduces a namedtuple `ArgumentCache` which can be provided as a minimal argument cache to Kapitan's cached module. This change ensures that our calls to Kapitan's compile_targets method continue working with Kapitan 0.29.3
[PR#625]: https://github.com/deepmind/kapitan/pull/625

Provide inventory_path in Kapitan's argument cache

---

.github/workflows/test.yml
CHANGELOG.md
commodore/component/template.py
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_component.py

When creating/removing components with `commodore component new` and `commodore component delete`, we need to also update the jsonnetfile.json and rerun jsonnet-bundler to ensure that the symlinks in `vendor/` exist.
Otherwise, `commodore catalog compile --local` fails after adding a component with `commodore component new`.

Adjust component new/delete to update jsonnetfile.json

---

commodore/config.py

Python 3.9 changed typing.NamedTuple to be a function that can be inherited from. This trips up pylint, cf. https://github.com/PyCQA/pylint/issues/3876.

Silence pylint error for class inheriting from NamedTuple

---

commodore/component/compile.py
tests/test_component.py
tests/test_component_compile.py

Remove unnecessary and wrong reinitialization of the `Component()` object in `commodore component compile`.
Also update the `run component compile` test to verify that the repo remotes are not changed.
Originally noticed in https://github.com/projectsyn/component-espejo/pull/8

Fix component compile to not break existing remote in component repo

---

commodore/dependency_mgmt.py
tests/test_dependency_mgmt.py

* Fix `fetch_components` to only fetch discovered components, instead of the full list of components with URL overrides.
* Fix `write_jsonnetfile` to transform `config.inventory.lib_dir` to string before dumping as JSON.

Fix regressions in dependency management

---

commodore/component/__init__.py
tests/test_dependency_mgmt.py

`os.listdir` doesn't preserve path information, so the appended `P(file)` entries which were returned by lib_files were just directly relative to the working directory, leaving dangling symlinks in `dependencies/lib` after symlinking the component files.

Fix Component.lib_files to produce proper paths

---

commodore/component/__init__.py
tests/test_component.py

Previously, Component.checkout would fail to update a component to a new version, if the local branch already exists but there's a newer upstream version.
This commit adjusts Component.checkout to always update the local branch to the latest upstream commit, discarding uncommitted local changes if any exist.
Closes #257.

Fix component checkout when local repo already contains the requested branch

---

CHANGELOG.md
commodore/component/__init__.py
commodore/dependency_mgmt.py
tests/test_component.py
tests/test_dependency_mgmt.py

This PR updates `dependency_mgmt.set_component_versions` to use `Component.checkout` instead of `git.checkout_version` to check out component repo to the selected version.

Correctly create a local branch when overriding component version

---

.github/workflows/push.yml
CHANGELOG.md

Remove usage of deprecated ::set-env in GitHub actions

---

.github/workflows/push-kapitan.yml
CHANGELOG.md

This image is used by Syn ArgoCD to reveal secrets in the compiled catalog.
Until now, we've built the image manually and pushed it to docker.io/vshn/kapitan.
This commit also moves the image to docker.io/projectsyn/kapitan

Add a GitHub action to build the Kapitan docker image

---

CHANGELOG.md
commodore/compile.py
commodore/config.py
commodore/dependency_mgmt.py
docs/modules/ROOT/pages/reference/architecture.adoc

This commit addresses the issue reported in #268, where we found that if a component is only included in aliased forms, the plain component is rendered to the catalog in addition to the aliased versions.
This commit changes component discovery to handle unaliased components as if they were aliased to the component name itself.
This change in discovery allows us to only generate targets for aliases which correctly doesn't create a target for the unaliased version of a component if it's only included in aliased form.
Fixes #268.

Always create targets from component aliases

---

CHANGELOG.md
commodore/compile.py
commodore/config.py
commodore/refs.py
tests/test_refs.py

Previously, we simply used the bootstrap target's `parameters` to generate Kapitan secret reference files. This approach doesn't support using `${_instance}` in secret references.
However, supporting that pattern is desirable, as it allows configuring sensible per-instance secret references in components which support instantiation.
This commit refactors Commodore's reference discovery and Kapitan reference file creation to correctly create reference files for "instantiated" secret references.
The refactored reference discovery iterates over all component instances and generates secret references for the component's key in `parameters` of the instance targets.
Just processing the component's key in `parameters` of the instance targets would not necessarily discover all secret references, …

Correctly handle component instances in Kapitan reference management

---

CHANGELOG.md
commodore/cluster.py
commodore/compile.py
commodore/component/__init__.py
commodore/component/compile.py
commodore/config.py
commodore/refs.py
docs/modules/ROOT/pages/reference/architecture.adoc
docs/modules/ROOT/pages/reference/concepts.adoc
tests/test_component.py

Enable hierarchy-based customization for the `jsonnetfile.json` of components.
As an example, this allows users to specify versions of their jsonnet dependencies in the hierarchy (e.g. kube-prometheus version based on cluster K8s version). See https://github.com/projectsyn/component-rancher-monitoring/pull/1 for an example.
Fixes #213

 Support for rendering component `jsonnetfile.json` from Jsonnet

---

CHANGELOG.md
commodore/component/__init__.py
docs/modules/ROOT/pages/reference/architecture.adoc
tests/test_component.py

This change assumes that most Git hosting services will use the pattern `ssh://git@example.com/path/to/repo.git` for SSH-based push URLs.
We configure each component repo's push-URL using the assumed substitution. This may not always generate a working push-URL, but for popular services like GitHub and GitLab, this removes the need of manually fixing the origin remote when trying to push a feature branch.

Generate a best-effort SSH-based push URL for component repos

---

CHANGELOG.md
commodore/cluster.py
commodore/compile.py
commodore/dependency_mgmt.py
commodore/helpers.py
docs/modules/ROOT/pages/reference/architecture.adoc
docs/modules/ROOT/pages/reference/concepts.adoc
tests/bench_component.py
tests/test_dependency_mgmt.py

This commit removes the `components` list in `commodore.yml` in the global config repository and instead looks for component URLs in `parameters.components`.
We deprecate `parameters.component_versions`, but to allow gradual migration to `parameters.components`, we merge
`parameters.component_versions` into `parameters.components` in the Kapitan targets.
Resolves #254

 Move component URLs to parameters.components

---

CHANGELOG.md
commodore/component/__init__.py
commodore/dependency_mgmt.py
docs/modules/ROOT/pages/reference/architecture.adoc
tests/bench_component.py
tests/test_dependency_mgmt.py

This commit removes the hard default version of "master" for components when there's no version specified in the hierarchy, and instead uses the default branch of the remote repository, which is indicated by `origin/HEAD`.

Default component version to "origin/HEAD" instead of "master"

---

CHANGELOG.md
commodore/compile.py
commodore/config.py
docs/modules/ROOT/pages/reference/deprecation-notices.adoc
docs/modules/ROOT/pages/reference/deprecation-policy.adoc
docs/modules/ROOT/partials/nav-reference.adoc
tests/test_config.py

Deprecation notice framework & initial deprecation warnings

---

CHANGELOG.md
commodore/cluster.py

Previously, for #284, we've merged component_versions into components in each Kapitan target.
This led to counter-intuitive behavior when trying to override versions in `components`, if the same component also has a version override in `component_versions`, as the override in `component_versions` would always have precedence over overrides in `components` regardless of their relative order in the hierarchy.
This component moves the merging of `component_versions` into `components` to the class `params.cluster` which has the lowest precedence of all classes.
This ensures that configuration in `components` has precedence over configurations in `component_versions` in all cases, while still allowing configurations which use `component_versions` to function.

Merge component_versions into components in `params.cluster`

---

CHANGELOG.md
commodore/component/__init__.py
tests/test_component.py

Tags show up as heads in the remote, but without the remote name as prefix. Previously the code would then try to checkout a branch with the name of the tag.
This commit makes the assumption that any heads in a remote which don't have the remote name as a prefix are tags, and handles checkout accordingly.
To keep the things simple, tags are checked out in detached HEAD state.

Correctly handle component versions which are tags

---

CHANGELOG.md
commodore/helpers.py
tests/test_helpers.py

By providing a custom implementation of `represent_str` and injecting it into PyYAML's dumper with `yaml.add_representer()`, we can control how multi-line strings are rendered.
This commit enables block-scalar style without trailing newline for any input strings which contain `\n`.
This will improve readability of catalog diffs for manifests which contain multi-line strings and have been processed by Commodore's postprocessing step.

Use block-scalars in Commodore's YAML dump helpers for multi-line strings

---

CHANGELOG.md
commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/test.yaml

The make target for running Vale has changed to `docs-vale` but the GitHub workflow configuration has not been updated to reflect this change.
This commit changes the workflow configuration to call `make docs-vale`.

Fix component template GitHub workflow to correctly lint docs

---

docs/modules/ROOT/pages/reference/architecture.adoc

nfs-client-provisioner has been deprecated in favor of nfs-subdir-external-provisioner

Rename nfs-client-provisioner to nfs-subdir-external-provisioner

---

CHANGELOG.md
commodore/compile.py
docs/modules/ROOT/pages/reference/deprecation-notices.adoc

The only use of this parameter is to fetch kube-libsonnet. This library is fetched by jsonnet-bundler since PR #246 has been merged.
Relates #255

Deprecate parameter `commodore.jsonnet_libs`

---

CHANGELOG.md
commodore/cli.py
commodore/compile.py
commodore/config.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/mock_git.py
tests/test_compile.py

These options are intended to be used to test changes to the global/tenant repo without relying on local compilation.
When either of the repo revisions are overridden using the command line flag, the resulting catalog cannot be pushed.
If a cluster catalog should actually be compiled and pushed using a different revision of the global or tenant repo, set the override in Lieutenant.
Relates to #198.

Add command line options to override global and tenant repo revisions

---

CHANGELOG.md
commodore/cli.py
commodore/cluster.py
commodore/compile.py
commodore/component/template.py
commodore/config.py
commodore/dependency_mgmt.py
commodore/helpers.py
docs/modules/ROOT/pages/local-mode.adoc
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_component_template.py

Since we moved to the target-per-component architecture in Commodore, the local mode of `catalog compile` got less usable, and required more manual steps for some changes (e.g. adding an additional component, cf. #297).
This PR changes local mode to discover components using the same mechanism as regular catalog compilation and also ensures Kapitan targets and component class symlinks in the Kapitan inventory are handled identically to regular catalog compilation.
This change also has the (wanted) side-effect that catalog compilation will fail in local mode if the config hierarchy uses parameter references which are not resolvable during inventory bootstrapping.
Additionally, this PR introduces a new command line flag for `catalog compile`, `--no-fetch-dependencies`, which turns off …

Improved local mode for `catalog compile`

---

CHANGELOG.md
commodore/component/compile.py

Update `component compile` to provide correct set of parameters that must be available, such as `cluster.tenant` and the mandatory `facts`.
This ensures that all components using only non-deprecated parameters can be compiled with `component compile`.

Update `component compile` to provide expected parameters

---

commodore/cluster.py
commodore/compile.py
docs/modules/ROOT/pages/reference/parameters.adoc
docs/modules/ROOT/partials/nav-reference.adoc
tests/test_cluster.py
tests/test_target.py

This commit adds parameters `cluster.display_name` and `cluster.tenant_display_name` which can be used to insert the cluster's and tenant's display name in manifests.
The commit also adds a new documentation page which lists all the inventory parameters which are managed by Commodore and injected during catalog compilation.
Fixes #307.

Introduce inventory parameters for cluster and tenant display names

---

.github/workflows/push.yml
commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/release.yaml

* Adds a missing flag for detecting prereleases when releasing components. 
* Affects also the component template resp. generator, thus labelled "bug"

Fix prereleases not being applied when using release candidates

---

commodore/compile.py
commodore/component-template/{{ cookiecutter.slug }}/class/defaults.yml
commodore/config.py
docs/modules/ROOT/pages/reference/component-deprecation.adoc
docs/modules/ROOT/partials/nav-reference.adoc
tests/test_config.py

This PR introduces a new component parameter `_metadata` which is defined as constant in the component template. When adding the parameter to existing components users are responsible to ensure that they mark the parameter as constant (with the `=` prefix).
Further, this PR changes Commodore will print out deprecation notices for all components for which `parameters.<component-name>._metadata.deprecated` is `True`.

Implement support for deprecating components

---

tox.ini

Newer versions of mypy (>=0.900) require external packages for type information.
This commit installs the packages suggested by mypy:
```
commodore/helpers.py:9: error: Library stubs not installed for "requests" (or incompatible with Python 3.9)
commodore/helpers.py:9: note: Hint: "python3 -m pip install types-requests"
commodore/helpers.py:9: note: (or run "mypy --install-types" to install all missing stub packages)
commodore/helpers.py:9: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
commodore/helpers.py:10: error: Library stubs not installed for "yaml" (or incompatible with Python 3.9)
commodore/helpers.py:10: note: Hint: "python3 -m pip install types-PyYAML"
commodore/helpers.py:13: error: Library stubs not installed for "requests.exceptions" (or …
```

Install type dependencies for mypy linting

---

poetry.lock
pyproject.toml

Go back to Kapitan v0.29.4 because v0.29.5 has regressions in the bundled reclass module which break our usage of the `applications` array for adding and removing components in the hierarchy.
This regression is also the cause for #326.
This regression is fixed in Kapitan as of https://github.com/kapicorp/kapitan/pull/703, but there's no release including this PR yet.

Pin Kapitan to v0.29.4 to avoid regressions in v0.29.5

---

.github/workflows/push.yml

This notice is only shown when the release is created from a branch, and not if it's created from a commit id or tag, see [this discussion].
This PR ensures that all releases are created from branch "master" and therefore have the message showing how many commits have been added to "master" since the release.
[this discussion]: https://github.community/t/x-commits-to-branch-since-this-release-is-missing-part-2/1806

Fix releases to show "x commits to master since this release"

---

commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/release.yaml

Change the release GitHub action in the component template to show "x commits to master since this release" by ensuring the releases are referencing branch "master" of the component repo.

Show number of commits to master since the release in component releases

---

tests/test_kapitan_reclass.py
tests/testdata/inventory_apps/classes/test.yml
tests/testdata/inventory_apps/classes/test/params.yml
tests/testdata/inventory_apps/classes/test/specific.yml
tests/testdata/inventory_apps/targets/test.yml
tests/testdata/inventory_relative_refs/classes/test.yml
tests/testdata/inventory_relative_refs/classes/test/common.yml
tests/testdata/inventory_relative_refs/classes/test/specific.yml
tests/testdata/inventory_relative_refs/targets/test.yml
tests/testdata/inventory_yml_yaml/classes/a.yml
tests/testdata/inventory_yml_yaml/classes/b.yaml
tests/testdata/inventory_yml_yaml/targets/test.yml

0Implement tests to catch regressions in Kapitan's Reclass for features we actively use in Commodore.
This commit covers the following Reclass features:
* Support for mixed `.yml` and `.yaml` file extensions for classes
* Support for relative class references
* Support for removing entries from the `applications` array in classes included at the same hierarchy level. See https://github.com/kapicorp/reclass/pull/5 for a detailed explanation of this reclass feature.
Resolves #330

Implement simple regression tests for Kapitan's bundled Reclass

---

commodore/cli.py

The `.env` was only found if it is placed next to the virtualenv.
If the virtualenv is in another directory, then the `.env` was ignored and `commodore` failed.
Fix it by searching the `.env` in current directory.

Use current working directory when searching for .env

---

commodore/helpers.py

Kapitan has an option `force_fetch` to always fetch and update dependencies specified in `parameters.kapitan.dependencies`.
This commit sets that option to `True` to ensure component dependencies are always updated to their latest upstream variants.
This change removes the sometimes unwanted Kapitan behavior to keep stale dependencies, if the component either doesn't properly store dependencies in a version-specific directory, or if dependencies are specified with moving versions (e.g. `release-4.x` for OCP4 alert rule manifests).

Always fetch Kapitan dependencies

---

.github/workflows/test.yml
Makefile
commodore/config.py
tests/test_catalog_compile.py
tox.ini

Integration test for catalog compilation

---

commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/test.yaml
commodore/component-template/{{ cookiecutter.slug }}/class/{{ cookiecutter.slug }}.yml
tests/test_component_template.py

* Use correct make target for linting documentation
* Don't emit trailing empty line in `component/<component>.yml` when creating a component without post-processing filters
* Adds tests which run `make lint` on all variants of the rendered component template

Fix component template

---

commodore/component-template/{{ cookiecutter.slug }}/Makefile

See also / same as projectsyn/modulesync-control/pull/9.
Currently the `parameters.kapitan.dependencies.[].output_path` needs to be overridden for all dependencies in test compiles (`make test`).
See:
- https://github.com/projectsyn/component-cert-manager/blob/master/tests/defaults.yml#L9
- https://github.com/projectsyn/component-keycloak/blob/master/tests/builtin.yml#L10
- https://github.com/projectsyn/component-keycloak/blob/master/tests/external.yml#L10
This is not optimal. It can lead to errors if a developer forgets to update the `tests/` file. The "real" output can now differ from the test output. Additionally it won't scale for components like [`component-argocd`](https://github.com/projectsyn/component-argocd/blob/master/class/argocd.yml) where there are many dependecies.
This PR …

Add local dependencies search path in commodore test compile

---

commodore/component/compile.py
commodore/postprocess/__init__.py
commodore/postprocess/builtin_filters.py
commodore/postprocess/jsonnet.py
tests/test_postprocess.py

Previously, we didn't respect component aliases when determining whether we need to run postprocessing.

Correctly postprocess aliased components

---

commodore/cluster.py
tests/test_render_inventory.py

Previously, an error could occur when compiling a catalog containing an instantiated component for which no configurations were adjusted.
This commit ensures that the instance's key in `parameters` always exists.

Fix `render_target` to ensure instantiated components always compile

---

commodore/cli.py
commodore/component/compile.py
docs/modules/ROOT/pages/reference/cli.adoc
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_component_compile.py

Previously we faked "instances" when compiling components by just setting `parameters._instance`, but kept the target for component compilation as the component name. This leads to differences in the resulting files as seen by the postprocessing step depending on whether a component is compiled independently or as part of a cluster catalog.
This commit introduces an additional command line option to specify the target component alias to use when compiling a single component with `commodore component compile`.
When this option is given, `component compile` correctly configures an aliased component and creates a target for the alias instead of the component. This ensures that postprocessing sees identical paths in `compiled` regardless of whether the component is being compiled as part of a …

Implement option to specify target alias for `commodore component compile`

---

commodore/postprocess/__init__.py
commodore/postprocess/builtin_filters.py
commodore/postprocess/jsonnet.py
docs/modules/ROOT/pages/reference/architecture.adoc
tests/test_postprocess.py

Previously Commodore postprocessing filters had the hard-coded assumption that each component's output would appear in `compiled/<component-name>`. This is not true for instantiated components, whose output appears in `compiled/<instance-name>`.
This commit fixes the postprocessing implementation to correctly use `compiled/<instance-name>` rather than `compiled/<component-name>` as the base directory in which postprocessing filters are executed.
Replaces #355 

Fix postprocessing for instantiated components 

---

Makefile
commodore/cluster.py
docs/modules/ROOT/pages/.vale.ini
docs/modules/ROOT/pages/reference/architecture.adoc
docs/modules/ROOT/pages/reference/parameters.adoc
tests/test_cluster.py
tests/test_target.py

Implement a new property `dynamic_facts` on the `Cluster` class and use this property to populate a new Reclass parameter
`parameters.dynamic_facts`.
This is in preparation to allow components to consume the cluster version as reported by Steward, cf. https://github.com/projectsyn/steward/issues/63

Provide dynamic facts in Reclass hierarchy

---

commodore/component/__init__.py
commodore/component/compile.py
commodore/config.py
commodore/dependency_mgmt.py
commodore/helpers.py
commodore/postprocess/jsonnet.py

This PR fixes newly added pylint warnings:
```
commodore/helpers.py:47:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
```
Should we start to pin `pylint` to a fixed version?

Set explicit encoding to fix pylint warnings

---

commodore/component-template/{{ cookiecutter.slug }}/.editorconfig

`jsonnetfmt` already has a very opinionated formatter, which makes the linter superfluous and can lead to conflicts between `jsonnetfmt` and `editorconfig` linters.
See: https://github.com/projectsyn/component-backup-k8up/pull/36/checks?check_run_id=3221663321#step:3:10
It hit us again yesterday while onboarding https://github.com/projectsyn/component-system-upgrade-controller and today in https://github.com/projectsyn/component-kyverno. It is not possible to make both the jsonnet formatter and the editorconfig indent linter happy at the same time without ugly workarounds (putting everything in one line, append a character to the variable to get the correct indentation).

Exclude jsonnet files from indent linter

---

commodore/component-template/{{ cookiecutter.slug }}/.yamllint.yml
commodore/component-template/{{ cookiecutter.slug }}/Makefile
commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk

`find` works differently on GNU and BSD.
BSD find would need an -E option or have the backslash before the braces removed.

Make yamllint exludes work on both BSD and GNU

---

commodore/cluster.py

Pylint now suggests f-strings over regular string formatting, cf. https://github.com/projectsyn/commodore/pull/368/checks?check_run_id=3675123805

Use f-strings for repo_url errors in `Cluster` class

---

commodore/component-template/{{ cookiecutter.slug }}/Makefile
commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk

Default search paths for component compilation to `./dependencies` and the component directory. This ensures that the component's own component lib can be found during component compilation.

Update compile make targets in component template to support components with library

---

commodore/catalog.py

Ensure Commodore exits with exit code 1 on catalog push failures

---

Makefile

We always want to set the variable `__git_version__` in `commodore/__init__.py` to the Git version generated with `git describe` in make target `inject-version`, since we don't actually do this in the "Publish to PyPI" GitHub action.

Correctly inject Git version in CI package builds

---

.github/workflows/test.yml
tests/test_component_compile.py
tests/test_component_template.py
tests/test_postprocess.py

#358, commit https://github.com/projectsyn/commodore/commit/8670c014bb1cf4b583965a70ed2a5dc65f99c42c, introduced a copy-paste error in the test GitHub action, which from then on mistakenly ran the `bench` target instead of the `test` target.
As a consequence we didn't catch some test failures in #364.
This PR fixes both the copy-paste error in the action and the broken tests.

Fix unit tests

---

.gitignore
commodore/cli.py
commodore/inventory/__init__.py
commodore/inventory/parameters.py
commodore/inventory/render.py
docs/modules/ROOT/pages/reference/cli.adoc
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_cli.py
tests/test_inventory_parameters.py
tests/test_inventory_render.py

This PR introduces a new command group called `inventory` and a new command in that group called `inventory components`.
The new command `inventory components` calls reclass to render an already checked-out Commodore defaults repo and returns all components (URLs and versions) defined in that repo. The command has a repeatable optional argument `-f / --values` to specify additional inventory classes in YAML files.
Users should use `-f` to provide additional facts (such as the cluster's K8s distribution) to the command as well as providing default values for parameters which are used in the global defaults repo without a configured default.

Add CLI command to extract component versions and URLs

---

commodore/cli.py

We used `click.Path()` with `path_type=pathlib.Path` but this somehow didn't work as expected when I installed the Commodore package from PyPI.
Instead of spending a considerable amount of time investigating the root cause and trying to fix it, we just don't tell `click` to do the conversion and convert the provided path strings to `pathlib.Path` ourselves.

Fix unreliable path type conversion in `commodore inventory components`

---

commodore/component-template/{{ cookiecutter.slug }}/renovate.json
renovate.json

* Disables Renovate Dependency dashboard for commodore and component template
* Follows https://github.com/projectsyn/modulesync-control/pull/51
(Value of this Dashboard isn't that great)

Disable Renovate dependency dashboard

---

commodore/compile.py
commodore/dependency_mgmt.py
docs/modules/ROOT/pages/reference/deprecation-notices.adoc

The parameter has been deprecated since Commodore v0.6.0.
Fixes #255

Remove support for deprecated parameter `commodore.jsonnet_libs`

---

commodore/component/__init__.py
commodore/dependency_mgmt.py
tests/test_component_compile.py
tests/test_dependency_mgmt.py

Add trailing newline when writing a `jsonnetfile.json`

---

commodore/inventory/parameters.py
tests/test_inventory_parameters.py

We inject `_instance: global` when rendering the inventory to ensure that multi-instance related configurations which use `${_instance}` are rendered correctly.

Fix command `inventory components` for inventories which use `${_instance}`

---

Makefile
commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk

Especially on Podman systems, docker.io may not be the default, thus breaking image pulls.
Be explicit where to pull images from by configuring a registry.

Use absolute Docker Image URLs

---

commodore/dependency_mgmt.py
tests/test_dependency_mgmt.py

This commit adds logic to detect component aliases which alias another component used in the hierarchy.
To do this, we validate discovered components and aliases after parsing all `applications` array entries. This also allows us to provide all components which illegally map to the same alias.
The errors are still raw `KeyError` exceptions when running `commodore catalog compile`.
Fixes #344

Improve error messages for duplicate component aliases

---

commodore/catalog.py
commodore/helpers.py
poetry.lock
pyproject.toml
tests/test_helpers.py
tox.ini

We previously assumed that any 4xx replies from Lieutenant would be Lieutenant errors, and would therefore contain key `reason` in the response.
However, if you try to compile a cluster to which you don't have access with a restricted Lieutenant API token (e.g. a cluster or tenant SA token), you get a 403 response which doesn't contain a `reason` field.
This commit correctly handles this case, and produces a legible error message in this case.
Fixes #367

Properly handle 403 replies from Lieutenant

---

Makefile
commodore/component-template/{{ cookiecutter.slug }}/Makefile
commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk

By default the GID defined in commodore's Dockerfile is used, which may or may not match an existing user on the system.
This commit explicitly sets the group ID when starting containers.
Additionally, the PR sets the container `HOME` environment variable explicitly to ensure that Commodore can write files in the home directory. This is required for `make test` for components which download Helm charts.

Update component template to ensure files are generated with the correct GID

---

commodore/cli.py
commodore/inventory/lint_components.py
docs/modules/ROOT/pages/reference/cli.adoc
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_cli.py
tests/test_inventory_lint_components.py

Currently the only implemented linting error is warning about component specifications without explicit version.

Add new command `inventory lint`

---

.github/workflows/test.yml
commodore/component/__init__.py
poetry.lock
pyproject.toml

Kapitan 0.30.0rc1 also updates GitPython to 3.1.24, so we can enable support for all Python 3.9 versions again (cf. #358)

Update Kapitan to 0.30.0rc1

---

.github/workflows/test.yml
tools/entrypoint.sh

#402 updates the Docker base image to Debian bullseye, which changes the location of `libnss_wrapper.so` from `/usr/lib/libnss_wrapper.so`to `/usr/lib/x86_64-linux-gnu/libnss_wrapper.so`. Our tests didn't catch this, because we didn't run the Docker image after building it.
This PR adds a few things:
1. A step in the docker image build Github Action which runs the freshly built image
2. A check that the configured `libnss_wrapper.so` path exists in `/usr/local/bin/entrypoint.sh` of the Docker image. This should ensure that the GitHub Action fails when the location of the library changes
3. Update the entrypoint script to use the correct path for Debian bullseye

Fix `/usr/lib/libnss_wrapper.so` not found error in Docker image

---

commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk

This PR:
* Bumps Antora preview command docker image to vshn/antora-preview:3.0.0.1. This gives us a Antora preview which auto-refreshes the docs while the command is running and updates the image to one which contains the current VSHN Kroki instance URL.
* Only mounts `<component-dir>/docs` and `<component-dir>/.git` into the Docker container. This should avoid issues with Antora getting confused about paths in `vendor` not being readable in the container.
* Exposes port 35729 of the Docker container for the auto-reload browser plugin.
See also https://github.com/projectsyn/modulesync-control/pull/59

Update the component template docs preview command

---

commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk

See https://github.com/projectsyn/modulesync-control/commit/6fb6c819137032de5482ffbb439ce848f272421c for the related change in modulesync-control.

Bump `vshn/antora-preview` image in component template to 3.0.1.0

---

commodore/config.py
docs/modules/ROOT/pages/reference/architecture.adoc
docs/modules/ROOT/pages/reference/deprecation-notices.adoc
tests/test_config.py

This PR moves the preferred location for components to advertise multi-instance support to `parameters.<component_name>._metadata.multi_instance`.
The old parameter `parameters.<component_name>.multi_instance` is still supported, but Commodore emits a deprecation notice for each component which still uses the old parameter.
Fixes #317

Move component instantiation advertisement to `_metadata.multi_instance`

---

commodore/component-template/{{ cookiecutter.slug }}/README.md

The previous link presents a cert for *.apps.cloudscale-lpg-2.appuio.cloud which results in SSL_ERROR_BAD_CERT_DOMAIN.

Update link to Commodore site

---

commodore/dependency_mgmt.py
tests/test_dependency_mgmt.py

Commodore injects `kube-libsonnet` as a dependency when compiling a cluster catalog. This commit updates the code to use the latest available tagged kube-libsonnet version as of 2022-02-23.

Update default `kube-libsonnet` version to v1.19.0

---

tools/entrypoint.sh

Fix docker image if running on non-`x86` architectures

---

commodore/gitrepo.py
tests/test_gitrepo.py

This regression got introduced by #407

Fix `GitRepo.push()` when pushing to empty remote repository

---

commodore/cli.py
commodore/config.py
commodore/login.py
commodore/tokencache.py
docs/modules/ROOT/pages/reference/cli.adoc
docs/modules/ROOT/pages/reference/commands.adoc
poetry.lock
pyproject.toml
tests/test_cli.py
tests/test_config.py
tests/test_login.py
tests/test_tokencache.py
tox.ini

This PR introduces a `commodore login` command that fetches an `id_token` from the configured IDP and stores it in a cache at `~/.cache/commodore/token`. This cache is used to lookup API tokens if no token is explicitly set.
You can test the login with `lieutenant-dev` using 
```
export COMMODORE_API_URL="https://api-dev.syn.vshn.net"
export COMMODORE_OIDC_CLIENT=syn-lieutenant-dev 
export COMMODORE_OIDC_DISCOVERY_URL=https://id.test.vshn.net/auth/realms/VSHN-main-dev-realm/.well-known/openid-configuration
commodore login
commodore catalog compile c-glrf-test
```
I'm still  not very happy with the tests..
Things I still want to do, but not in this PR:
* Automatically call `commodore login` if there is no token in the cache / token is expired
* Return the client-id and discovery URL from …

Add OIDC integration for Lieutenant communication

---

commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk

While it was already possible to use podman by setting the DOCKER_CMD
env var, this was not enough for most commands.
This commit adds support for Podman out of the box. If Docker is
installed, it will be preferred over Podman to stay
backwards-compatible.
The `--userns=keep-id` flag is required on Podman to ensure that 1.) the
process in the container can write to the mounted workdirs, and 2.)
ensure files created by processes in the container have the correct owner
and group IDs: The ones from the user running the Make tasks.

Update component template to support Podman out of the box

---

commodore/login.py
tests/test_login.py

With this we are able to auto discover all configuration through lieutenant.
You should be able to do: 
```
COMMODORE_API_URL="https://api-dev.syn.vshn.net"  commodore catalog compile c-glrf-test
```
And commdore will find out where to authenticate and open a browser.

Auto discover OIDC configuration if not set

---

commodore/component-template/{{ cookiecutter.slug }}/Makefile
commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
tests/test_component_template.py

We want to be able to adjust which `commodore` to use without having to reproduce the full compile command when compiling individual components with `make test`, `make golden-diff` or `make gen-golden`.
This commit reduces `COMMODORE_CMD` to be the equivalent of a bare invocation of `commodore` and introduces a new variable `COMPILE_COMMAND` which corresponds to the previous value of `COMMODORE_CMD`.
The PR also updates the `golden-diff` test to run the Commodore binary under test instead of whichever container image is available locally as `projectsyn/commodore:latest`.

component-template: Split `COMMODORE_CMD` and `COMPILE_CMD` in Makefile 

---

.github/workflows/coverage.yml
.github/workflows/test.yml

This allows us to run only the coverage test run on pushes to master without having to resort to conditional jobs for all other tests.
We need to run the coverage report on pushes to master to actually get visible code coverage reports from codeclimate.
Follow-up for #439 

Move test coverage to own GitHub action

---

commodore/postprocess/__init__.py
docs/modules/ROOT/pages/reference/deprecation-notices.adoc
tests/test_postprocess.py

Commodore v0.4.0 introduced support for defining postprocessing filters in the component class. However, defining postprocessing filters in `postprocess/filters.yml` was never formally deprecated.

Deprecate external postprocessing filter definitions

---

commodore/compile.py
commodore/component/__init__.py
commodore/component/compile.py
commodore/dependency_mgmt.py
docs/modules/ROOT/pages/reference/architecture.adoc
docs/modules/ROOT/pages/reference/concepts.adoc
tests/test_component.py
tests/test_dependency_mgmt.py

Add support for component library aliases

---

commodore/catalog.py
tests/test_catalog.py

Refactor `_push_catalog()` to return early in local mode

---

commodore/helpers.py
tests/test_dependency_mgmt.py
tests/test_helpers.py

`Path.exists()` returns False for dangling symlinks. Until now, we used only `Path.exists()` to determine whether we need to remove the link target before creating a new symlink.
This PR checks both `Path.exists()` and `Path.is_symlink()` to determine whether we need to remove a link target before creating a new symlink.
This fixes an issue where Commodore can fail to replace dangling symlinks for components which have been changed to export component library aliases.
The PR also correctly raises the exception when source doesn't exist.
Will be backported to a v0.17.1 since the bug may break catalog compilations in existing Commodore working directories.

Correctly remove dangling link destinations in `relsymlink()` 

---

commodore/helpers.py
tests/test_dependency_mgmt.py
tests/test_helpers.py

[Backport 0.17] Fix removing dangling symlinks in `relsymlink()`

---

commodore/tokencache.py
tests/test_tokencache.py

We need to use `Dict.get()` to read a key which might not exist from the dictionary.
Will be backported to v0.17

Fix potential KeyError in `tokencache.get()`

---

commodore/tokencache.py
tests/test_tokencache.py

We need to use `Dict.get()` to read a key which might not exist from the dictionary.
Backport of #458 to v0.17

[Backport] Fix potential KeyError in `tokencache.get()`

---

commodore/catalog.py
tests/test_catalog.py

* Correctly ignore pair of lines if either line is an empty context line
* Correctly ignore multiple consecutive removed `null` objects in YAML stream
Follow-up to #450 

Fix edge cases in `_is_semantic_diff_kapitan_029_030()`

---

commodore/cluster.py
commodore/inventory/parameters.py
docs/modules/ROOT/pages/reference/deprecation-notices.adoc

We've moved to `parameters.components` to specify component URLs and versions in Commodore v0.5.0. This commit removes support for the deprecated parameter `component_versions` which we used before v0.5.0 to specify component version overrides.
Relates #375

Remove deprecated parameter `component_versions`

---

commodore/postprocess/__init__.py
tests/test_postprocess.py

Previously we could cause a `KeyError` when formatting an error message for a postprocessing filter which is missing the key `filter`.
This PR ensures that we create a nice error message in that case.
Additionally, we add tests covering different invalid postprocessing filter definitions.

Fix `KeyError` in error message for invalid postprocessing filters

---

renovate.json

We need to keep back `gitpython`, `requests` and `typing-extensions` because Kapitan depends on specific versions of those packages.
Follow-up to #471 

Add dependencies which shouldn't be updated to `ignoreDeps` in `renvoate.json`

---

commodore/compile.py
tests/test_compile.py

Relates #375
Removal of support for `parameters.component_versions` is already added as a breaking change in #454

Make usage of parameter `component_versions` an error

---

commodore/component/__init__.py

We don't support external postprocessing filter definitions anymore, so we don't need a property telling us where components used to define external postprocessing filters.
Follow-up for #453 

Remove unused property `Component.filters_file`

---

commodore/compile.py
tests/test_compile.py

We raise an error if we find any occurrences of removed reclass variables (cf. #460) in the cluster's global defaults, tenant repo, or
any enabled components. 
The global and tenant repo are linted before we try to fetch or register components, so that we always are able to produce nice errors instead of a reclass stack trace if the inventory contains usages of removed parameters.
For the components, we check the `defaults.yml` and `<component-name>.yml` of each included component after fetching or registering the cluster's components.

Raise error when compiling a cluster which uses removed reclass variables

---

commodore/compile.py
commodore/component/compile.py
commodore/inventory/lint.py
tests/test_compile.py
tests/test_inventory_lint.py

Follow-up to #460 and #482, but for `commodore component compile`.
For component compilation, the check raises an error if the component's `defaults.yml`, `<component-name>.yml` or any of the additional class files provided via command line arguments uses a removed reclass variable.

Raise error when compiling a component which uses removed reclass variables

---

Dockerfile
commodore/login.py
docs/modules/ROOT/pages/explanation/running-commodore.adoc

This PR makes the changes which are necessary to allow users which run Commodore in Docker to use Commodore's OIDC login feature. The documentation is also updated with the newly required command line arguments for Docker.
Fixes #491 

Fix Commodore OIDC login when running in Docker

---

commodore/login.py

Without `url_normalize()`, auto-discovery doesn't work for users which set `COMMODORE_API_URL` to a hostname without a scheme because the `requests` library raises an Exception for URLs without a scheme.
Additionally, the PR adds an informational message containing the exception summary when OIDC auto-discovery fails with an Exception in the `requests.get()` call.

Use `url_normalize()` when auto-discovering OIDC config

---

commodore/component/__init__.py
tests/test_component.py

This fixes compile errors regarding invalid library names when trying to compile a component or catalog while an editor swap file (e.g. vim swap file) is present in a component library directory.

Skip hidden files when enumerating component library files

---

commodore/cli.py
commodore/config.py
commodore/package/compile.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_package_compile.py

Add command line flags `--local` and `--no-fetch-dependencies` with the same semantics as for `catalog compile`.
Follow-up for #505 
Resolves #499

Add flags `--local` and `--no-fetch-dependencies` for `package compile`

---

commodore/compile.py
commodore/helpers.py
commodore/package/compile.py

This parameter is clearly redundant, since we only ever set it to `config.fetch_dependencies`, while simultaneously passing the config object to the function.
Follow-up from #506 

Remove redundant parameter `fetch_dependencies` of `kapitan_compile`

---

commodore/cli.py
commodore/package/template.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_package_template.py

Requires https://github.com/projectsyn/commodore-config-package-template/pull/3

Add support for adding additional test cases in new config packages

---

commodore/cli.py
commodore/package/compile.py
docs/modules/ROOT/pages/reference/cli.adoc
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_package_compile.py

Some packages may require that some configuration is provided in an additional class file, for example cluster facts may be used to include additional classes by the package.
Generally, users should define test cases in `tests/` in the package directory and have each test case class include the desired target class of the package in the test class's `classes` array. Note that relative includes are always interpreted relative to the class containing the include. Reclass supports the prefix `..` to include a class from the parent directory.

Change `package compile` target class to be provided as a path

---

commodore/cli.py
commodore/package/compile.py
docs/modules/ROOT/pages/reference/cli.adoc
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_package_compile.py

Otherwise, we can't reliably avoid situations where we create infinitely deep directory structures when symlinking the package to `inventory/classes`.

Change `package compile` to always use a temporary directory

---

poetry.lock
pyproject.toml
renovate.json

We use `oauthlib` in `commodore/login.py` but didn't explicitly specify the dependency until now.

Explicitly specify `oauthlib` as a dependency

---

poetry.lock
pyproject.toml
renovate.json

We use `pyjwt` (`import jwt`) in `commodore/config.py`, but didn't explicitly specify the dependency until now.
Follow-up to #515 

Explicitly specify `pyjwt` as a dependency

---

commodore/component-template/{{ cookiecutter.slug }}/.gitignore

We only want to ignore the directories created by Commodore in the component root. With the current component template `.gitignore`, we may accidentally ignore folders in the golden test output, or elsewhere.
Part of https://github.com/projectsyn/modulesync-control/issues/77

Fix component template `.gitignore` entries

---

commodore/catalog.py

We've previously had to carefully clean the catalog before updating the Kapitan secret refs (cf. #50), as we'd otherwise delete the regenerated ref files during the initial catalog compilation for a cluster.
This was caused by the logic implemented in https://github.com/projectsyn/commodore/commit/a75c903d461664b4567e44d5c649c81e52e4d160 which was there to convert catalogs from the original format where
manifests were directly stored in the root of the catalog repo to the current format where we have top-level directories `manifests` and `refs` in the catalog repo.
In #505, we've refactored the catalog compile logic to support config packages. While doing so, we've accidentally moved `catalog_clean()` after the logic which regenerates the ref files, thus breaking initial compilation of …

Fix bug in catalog update logic for initial compilation of a cluster

---

commodore/component-template/{{ cookiecutter.slug }}/.gitignore

We need to add `/dependencies` to the component template gitignore file, as `commodore component compile` creates that directory when fetching component dependencies for all components which haven't been migrated to use `${_base_directory}` instead of hardcoding their location relative to the commodore working directory.
Relates to https://github.com/projectsyn/modulesync-control/pull/81
Follow-up to #528

Add `/dependencies` to component template `.gitignore`

---

commodore/component-template/{{ cookiecutter.slug }}/Makefile
commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk

The `lint_kubent` target runs `kubent` on a single golden test instance, defaulting to instance `defaults`. The commit also adds a target `lint_kubent_all` which will run `kubent` for all targets separately.
We don't run `kubent` over all golden tests simultaneously because the tool doesn't support linting multiple Kubernetes objects with the same name and namespace in a single run.
The commit ensures that the `kubent` lint targets are only added to components which are created with golden tests enabled.
See also https://github.com/projectsyn/modulesync-control/pull/82

component-template: Add `lint_kubent` make targets to check for deprecated API versions

---

commodore/dependency_mgmt/__init__.py
commodore/package/__init__.py
commodore/package/compile.py
docs/modules/ROOT/pages/reference/concepts.adoc
tests/test_dependency_mgmt.py

Instead of cloning packages directly into `inventory/classes` we now clone them to `dependencies/pkg.{package-name}` and symlink them into `inventory/classes`.
This is a first step towards supporting dependencies in repository subdirectories, and unifies the location for cloned component and package repositories in the Commodore working directory.
Part of #518 

Clone config packages to `dependencies/pkg.{package-name}`

---

commodore/cli.py
commodore/component/__init__.py
commodore/component/compile.py
commodore/dependency_mgmt/__init__.py
commodore/dependency_mgmt/jsonnet_bundler.py
commodore/dependency_mgmt/version_parsing.py
commodore/package/__init__.py
docs/modules/ROOT/pages/reference/architecture.adoc
docs/modules/ROOT/pages/reference/concepts.adoc
tests/test_component_compile.py
tests/test_dependency_mgmt.py
tests/test_dependency_mgmt_version_parsing.py

This PR adds support for storing dependencies (components and packages) in a subpath of a repository. This is a prerequisite for supporting repositories which contain multiple dependencies.
Currently, Commodore will clone a repository multiple times if multiple dependencies are stored in the same repository. We'll introduce repository deduplication in a follow-up PR (#549).
Part of #518 

Add support for dependencies in repository subpaths

---

commodore/component/__init__.py
commodore/component/compile.py
commodore/component/template.py
commodore/config.py
commodore/dependency_mgmt/__init__.py
commodore/gitrepo.py
commodore/multi_dependency.py
commodore/package/__init__.py
docs/modules/ROOT/pages/reference/architecture.adoc
tests/conftest.py
tests/test_component.py
tests/test_component_compile.py
tests/test_config.py
tests/test_dependency_mgmt.py
tests/test_dependency_mgmt_jsonnet_bundler.py
tests/test_gitrepo.py
tests/test_helpers.py
tests/test_inventory.py
tests/test_multi_dependency.py
tests/test_package.py
tests/test_package_compile.py
tests/test_postprocess.py
tests/test_render_inventory.py

This PR changes how Commodore handles dependencies to implicitly assume that any set of dependencies may share a repository. To faciliate this, the PR changes the disk layout for the checked out dependencies to use git worktree with a bare "main" clone of the repository stored in dependencies/.repos/git.host/path/to/repo.git where the path under dependencies/.repos is constructed from the remote URL.
Resolves #518 
Replacement for #549 which got closed accidentally.

Refactor dependency repository handling to avoid multiple clones of the same repository

---

commodore/package/template.py
tests/test_package_template.py

We forgot to update `package new` to create the new packages in `dependencies/` when changing Commodore to symlink packages from `dependencies` into the inventory.
Follow-up to #546

Update `package new` to save the new package in `dependencies/`

---

commodore/component/template.py
commodore/dependency_templater.py
commodore/gitrepo.py
commodore/multi_dependency.py
commodore/package/template.py
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_component_template.py
tests/test_gitrepo.py
tests/test_multi_dependency.py
tests/test_package_template.py

Only create worktrees when creating components or packages in a Commodore working tree (i.e. as subdirectories of `dependencies/`).
We also change the generic dependency template rendering to always render the template in a temp directory and moving the result into the final location, because we can't make an existing directory a Git worktree and cookiecutter doesn't support rendering a template into an existing directory, so we need to create the worktree first, then copy the templated dependency into it.
Follow-up to #551 

Create new components and packages as Git worktree checkouts

---

commodore/cli.py
commodore/package/template.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_package_template.py

We previously didn't deduplicate the set of test cases requested when creating or updating a package. This can lead to noisy updates when users specify a new test case which already exists in the package.
This commit adds logic to remove duplicates in the getter for the list of test cases.  We deduplicate the list in the getter rather than the setter, to avoid introducing invisible duplicates if users use `append()` on the returned list.

Deduplicate requested test cases for `package new` and `package update`

---

commodore/cli.py
commodore/cluster.py
commodore/config.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_catalog_compile.py
tests/test_cluster.py
tests/test_config.py

We support providing dynamic facts as `--dynamic-fact key=value` in command `catalog compile`. The key can specify a nested key as `path.to.key`, and the value can optionally be parsed as JSON if it's prefixed with a literal `json:`. Facts specified later on the command line take precedence over previously specified facts. Nested facts will not be considered if one of their key segments (except the leaf) already holds a non-dictionary value.
Dynamic facts provided on the command line are only used for catalog compilation when the Lieutenant API response for the cluster which is getting compiled doesn't contain field `dynamicFacts`.
This enables us to cleanly support compilation of a cluster catalog before Steward is deployed on the cluster.
`bug`, `enhancement`, `documentation`, `change`, …

Add flag for providing fallback dynamic facts for `catalog compile`

---

commodore/config.py
commodore/login.py
commodore/tokencache.py
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_config.py
tests/test_login.py
tests/test_tokencache.py

We implement OIDC token refresh if our access token is expired, but we still have a valid refresh token in the tokencache for the current Lieutenant URL. If the token refresh succeeds, we short-circuit `login()` without performing a browser-based login.
If the token refresh fails for any reason, we fall back to browser-based login.
Closes #494 

Add logic to try refreshing OIDC token in `login()`

---

commodore/cli.py
commodore/inventory/render.py
docs/modules/ROOT/pages/reference/cli.adoc
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_cli.py
tests/test_cli_functions.py

This PR introduces tow new command for the command group `inventory`.
The command `inventory packages` is the equivalent to `inventory components`. It calls reclass to render the inventory of a global defaults or tenant repo and returns all packages (URLs and versions) defined in that repo.
The command `inventory show` also renders the inventory, but returns all parameters, not just package or component infos.
Both commands can take an extra values file and can return the output in json or yaml

Add CLI commands to extract package versions and show rendered inventory

---

commodore/cli.py
commodore/inventory/parameters.py
tests/test_cli_functions.py

If we set `allow_missing_classes=True` reclass will not fail if a referenced class does not exist. However it will still print a warning to stdout. This results in invalid JSON/YAML output for `commodore inventory show|components|packages` as it will start with one or more log lines if a class is not found.
With this PR we explicitly disable reclass wanings when calling `commodore inventory show --allow-missing-classes`.

Remove reclass warnings from `commodore inventory show` output

---

commodore/cli.py
commodore/package/sync.py
docs/modules/ROOT/pages/reference/commands.adoc

Follow-up for #572. Labeled as `ignore` since `package sync` has not been released yet.

Use each repo's default branch as the PR base branch for `package sync`

---

tox.ini

This is necessary to allow the tests to use SSH keys stored in the agent when running tests locally.

Pass `SSH_AUTH_SOCK` environment variable to tox-based tests

---

poetry.lock
pyproject.toml
tools/tools.py

We've switched to Black for code formatting a while ago, so we don't actually need `autopep8` as a dev dependency anymore.

Remove development dependency `autopep8`

---

docs/modules/ROOT/pages/explanation/running-commodore.adoc

We need to mount the host working directory into the same location in the container so that `git worktree` based checkouts of components and packages are valid both on the host and in the container.
This needs a identity-mapping of the working directory because Git uses the absolute path to the git directory when creating a worktree checkout.

Update suggested Commodore-in-Docker helpers

---

commodore/login.py
tests/test_login.py

We added more tests for `login.py` a while ago. Those tests introduced a race condition between test cases as we have two different tests which try to bind to port 18000 to test the OIDC callback handler.
This commit makes the port configurable, and uses a different port for the callback handler unit tests.

Ensure that there's no chance that test cases compete for ports

---

commodore/cli.py
commodore/component/__init__.py
commodore/component/compile.py
docs/modules/ROOT/pages/reference/cli.adoc
docs/modules/ROOT/pages/reference/commands.adoc
docs/modules/ROOT/pages/reference/deprecation-notices.adoc
tests/test_cli_functions.py
tests/test_component.py
tests/test_component_compile.py

We don't need users to provide the location of the repo directory in `component compile` since we strictly speaking don't need the component to even be in a Git repository for standalone compilation. We  use GitPython's `search_parent_directories=True` to try to find the repo in which the provided target dir is located, but fall back on just using the indicated target directory as the component directory for standalone compilation.
If we find a Git repository holding the component, we compute the component subpath based on the relative location of the target directory to the repo working tree directory. In this case, we use the working tree directory of the repo as the component "target directory" so that standalone compilation of a component stored in a repo subdirectory is as close as …

Deprecate parameter `--repo-directory` for component compile

---

commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk

Update Makefile.vars.mk to support both regular Git checkouts and Git worktree checkouts using a OS-agnostic .git symlink.
Related modulesync PR: https://github.com/projectsyn/modulesync-control/pull/83

Add logic in component template `Makefile.vars.mk` to handle Git worktree checkouts

---

commodore/component/__init__.py
tests/test_component.py

We gracefully degrade in `render_jsonnetfile_json()` and don't print a warning if both `jsonnetfile.json` and `jsonnetfile.jsonnet` are present in the component directory, if we can't detect a Git repository for the component.
Follow-up to #582, labelled `ignore` since #582 isn't released yet.

Fix `Component.render_jsonnetfile_json()` when no repo detected

---

commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk

This should reduce the amount of patching required when setting up a component in a subdirectory from the template.
Modulesync PR: https://github.com/projectsyn/modulesync-control/pull/84

Hard-code component name in component template `Makefile.vars.mk`

---

Dockerfile
docs/modules/ROOT/pages/explanation/running-commodore.adoc

We update the Commodore `Dockerfile` to install `gpg` and initialize the `~/.gnupg/` directory in the container. Additionally, we update the Commodore-in-Docker command for Linux to ensure that Git commits can be GPG-signed in the container when the user's `.gitconfig` contains `commit.gpgsign=true`. To allow this, we mount the user's `pubring.kbx` and the user's GPG `agent-extra-socket` in the container, if GPG is available and configured.
We check for availability by looking for the `gpgconf` command on the host system, and for configuration by looking for the user's
`pubring.kbx`.
Please note that the Commodore-in-Docker command for macOS doesn't provide out-of-the box support for GPG-signing commits in the container at this time.
Resolves #579 
`bug`, `enhancement`, `documentation`, …

Update Commodore-in-Docker to support GPG-signing commits on Linux

---

commodore/inventory/lint_dependency_specification.py
tests/test_inventory_lint_components.py

In Commodore v1.4, we introduced support for storing dependencies in subpaths of repositories. However, we didn't update the dependency specification linting to allow the new key `path` which is used to indicate the subpath.
This commit updates the dependency specification linting to allow key `path` in component and package specifications.

Fix dependency spec linting for dependencies in subpaths

---

commodore/cli.py
commodore/component/template.py
commodore/dependency_templater.py
commodore/package/template.py
docs/modules/ROOT/pages/reference/cli.adoc
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_component_compile.py
tests/test_component_template.py
tests/test_package_compile.py
tests/test_package_sync.py
tests/test_postprocess.py

Currently the command supports enabling or disabling golden tests, matrix tests, the component library and component postprocessing filters.
We'll add support for managing test cases in a follow-up change.
The PR also reorganizes a lot of the template rendering code, moving code which is now useful for both components and packages to the `Templater` base class.

Add new command `component update`

---

commodore/compile.py

Previously, we didn't pass the provided Git author name and email when cloning the global and tenant repo in `catalog compile`. This can cause unexpected errors on setups where GitPython can't infer user information from either the Git config file or the UID of the process (e.g. GitLab CI runners in K8s pods).
This change ensures that we pass provided Git author information when creating GitRepo objects for the global and tenant repos. This should ensure that there's no errors if `GIT_AUTHOR_NAME` and `GIT_AUTHOR_MAIL` are set for environments which don't have sufficient information for GitPython's author information fallback mechanism.
Replacement for #597 which got closed accidentally
as they show up in the …

Correctly pass Git author name and email in `catalog compile`

---

commodore/cli.py
commodore/component/template.py
commodore/dependency_templater.py
commodore/package/template.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_component_template.py

This PR adds support for generating additional test cases to `component new`. Commodore will ensure that components are always created with matrix tests enabled if more than one test case is requested. This feature requires https://github.com/projectsyn/commodore-component-template/pull/6.

Add option to create additional test cases for `component new`

---

commodore/config.py
commodore/multi_dependency.py

Follow-up to https://github.com/projectsyn/commodore/pull/598.
We also need to pass through the provided Git author name and email when registering dependency repositories to ensure `catalog compile` works correctly in environments which don't support GitPython's fallback mechanism to determine author information.

Correctly pass Git author name and email to dependency repos

---

commodore/component/__init__.py
commodore/package/__init__.py
tests/test_component.py

We don't always create a `MultiDependency` for component or package objects, so we need to ensure `Component.repo` works correctly even if `Component._dependency` is `None`.
This commit ensures that we fall back to using `None` for the Git author name and email if we don't have a `MultiDependency` for a component or package.
Follow-up to #598, #602, #603, #604

Fix GitRepo initialization for dependencies without backing MultiDependency

---

commodore/cli.py
commodore/dependency_templater.py
commodore/package/template.py
docs/modules/ROOT/pages/reference/cli.adoc
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_component_template.py

This PR adds new flags to `component update` which allow users to add or remove test cases.
The PR also makes removing all test cases with `component update` or `package update` an error, since the templates currently don't cleanly support having no test cases at all.

Add support for adding and removing test cases to `component update`

---

tools/entrypoint.sh

On Kubernetes runners, we already create the `.ssh` folder prior to
running the entrypoint script. This leads to an error in the script, as
it can't create the `.ssh` folder.
Signed-off-by: Nicolas Bigler <nicolas.bigler@vshn.ch>

Fix entrypoint script in case the `.ssh` folder already exists

---

commodore/dependency_templater.py
commodore/gitrepo.py
tests/test_component_template.py
tests/test_gitrepo.py

This PR aborts `component update` and `package update` if Cruft's `update()` returns `False`. Additionally, we add logic to `GitRepo.stage_all()` and `GitRepo.stage_files()` to raise an exception on merge conflicts in the files to be staged.

Explicitly handle Cruft errors and merge conflicts in `Templater.update()`

---

commodore/component/template.py
commodore/dependency_templater.py
tests/test_component_template.py

If we don't have the copyright info for a component in the Cruft cookiecutter args, fall back to reading it from the component's
modulesync config (`.sync.yml`) or use the default values used by modulesync, if the component's `.sync.yml` doesn't have the information either.

Add fallback to extract copyright info from modulesync config

---

commodore/dependency_syncer.py
commodore/dependency_templater.py
commodore/gitrepo.py
tests/test_component_template.py

This PR adds an optional argument for `Templater.update()` which configures a custom diff function which suppresses `.cruft.json` diffs which only contain a changed template commit id.
This allows us to change `sync_dependencies()` to call `update()` with `ignore_template_commit=True` to ensure the sync doesn't create PRs for updates which only modify the template commit id for template updates which make changes in a part of the template which only applies to a few dependencies.
Fixes #632 

 Change `sync_dependencies()` to omit PRs which only update the template commit id

---

commodore/cli.py
commodore/dependency_syncer.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_cli_functions.py
tests/test_dependency_sync.py

We change `sync_dependencies()` to pause for 2 minutes (120 seconds) after creating batches of 10 PRs. The length of the pause is configurable as a command line option for commands `component sync` and `package sync`.
Fixes #617 

Improve handling of secondary rate limits in `sync_dependencies()`

---

commodore/dependency_templater.py

With the updated `GitRepo.stage_all()` implementation (cf. #633), we no longer need to explicitly stage hidden files as the new `stage_all()` implementation will ensure that new hidden files are staged.

Remove `Templater.additional_files` which is not needed anymore

---

.github/PULL_REQUEST_TEMPLATE.md
.github/changelog-configuration.json

This allows us to separate changes which impact the user from changes that are purely internal to the Commodore code base in the changelog.
Additionally, the commit ensures that breaking changes will appear at the top of the changelog.

Add new label `internal` for PRs which make purely internal changes

---

commodore/__init__.py
commodore/cluster.py
commodore/component/compile.py
commodore/lib/commodore.libjsonnet
commodore/scripts/run-kustomize
docs/modules/ROOT/pages/reference/commodore-libjsonnet.adoc
docs/modules/ROOT/pages/reference/parameters.adoc
pyproject.toml
tests/test_component_compile.py
tests/test_target.py

Provide the absolute path to the script in reclass variable `${_kustomize_wrapper}`, to allow users to make use of Kustomize without having to worry about the binary location being different on different systems.
The PR also provides a new function in `commodore.libjsonnet`, which generates an object which is suitable as a Jsonnet output to render a `kustomization.yaml` which can be processed by `kustomize build`.
See https://github.com/projectsyn/documentation/pull/169 for extended documentation.
Closes #504 

Improve support for `kustomize` in Commodore

---

commodore/inventory/lint.py
tests/test_inventory_lint_components.py

Until now, we didn't check whether a top-level key `parameters` is actually a dict, which caused a crash in the linter when a non-inventory file (e.g.  an OpenShift template) has such a top-level key.
This commit simply skips files which have a top-level key `parameters` which isn't a dict.
Part of #659

Avoid crash in `inventory lint` when top-level `parameters` is not an object

---

commodore/cli.py
commodore/inventory/lint.py
docs/modules/ROOT/pages/reference/cli.adoc
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_inventory_lint_components.py

Patterns can be provided either on the command line in `--ignore-patterns` or in a `.commodoreignore` file in the linting
target path. Patterns given on the command line apply for each target path, while `.commodoreignore` applies only for the target path in which the file is present.
Patterns are expanded recursively using Python's `glob` library.  You can use `*`, `?`, and character ranges expressed as `[]` with the usual semantics of shell globbing, and `**` to indicate an arbitrary amount of subdirectories. Patterns which start with `/` are treated as anchored in the target path, while other patterns are treated as matching any subpath in the target path.
Part of #659 
as they show up in the …

Implement ignore patterns for `inventory lint`

---

commodore/cli/component.py
commodore/cli/options.py
commodore/cli/package.py
commodore/dependency_syncer.py
docs/modules/ROOT/pages/reference/cli.adoc
docs/modules/ROOT/pages/reference/commands.adoc
tests/test_cli_component.py
tests/test_cli_package.py
tests/test_dependency_sync.py

This PR implements a new option `--filter REGEX` for `component sync` and `package sync`. This option allows callers to selectively sync only dependencies which match the provided regex. The base set of dependencies is still always loaded from the given YAML file.
In the dependency syncer implementation, the PR moves loading and filtering of the dependency file into a separate function.
Resolves #615 

Add support for selective dependency syncing

---

commodore/inventory/lint.py
commodore/inventory/lint_dependency_specification.py
tests/test_inventory_lint_components.py

We can now ignore files which shouldn't be linted (cf. #665), so we can make a non-dictionary key `parameters` in a Commodore inventory file a lint error instead of skipping such files.
Fixes #659

Make non-dictionary key `parameters` a linting error

---

renovate.json

We don't really need the "Lock file maintenance" PRs to show up in the Commodore release notes. This commit sets label `ignore` to explicitly mark those PRs as not relevant for the changelog.

Label Renovate lockFileMaintenance PRs with `ignore`

---

commodore/dependency_mgmt/jsonnet_bundler.py
commodore/helpers.py
commodore/inventory/__init__.py
commodore/inventory/parameters.py

Mypy has started to emit the following error for arguments with default values which don't match the argument's type annotation:
```
error: Incompatible default for argument "cloud" (default has type "None", argument has type "str")  [assignment]
note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
```
This commit fixes all occurrences of this new error in the Commodore code base.
Discovered in #683 

Add missing `Optional` to function arguments with default value `None`

---

docs/modules/ROOT/pages/explanation/running-commodore.adoc

without the change the gpg opts would be passed to `docker run` as a single argument instead of two separate arguments.
Not sure if there is a better option to do this or in which shell/version combination this should've worked :) 

Fix mounting of GPG agent to Commodore docker container on Linux

---

.github/workflows/coverage.yml
.github/workflows/publish-pypi.yml
.github/workflows/test.yml

GitHub doesn't provide repo secrets to actions running for PRs whose head branch is from a fork. We have some actions which don't work without the secrets, see e.g. #686 . This PR disables these actions for PRs from forks.

Skip GitHub actions which need additional secrets on PRs from forks

---

commodore/cli/catalog.py
commodore/compile.py
commodore/component/__init__.py
commodore/dependency_mgmt/__init__.py
commodore/gitrepo.py
commodore/gitrepo/__init__.py
commodore/gitrepo/diff.py
commodore/package/__init__.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_compile.py
tests/test_component.py
tests/test_dependency_mgmt.py
tests/test_gitrepo.py
tests/test_gitrepo_diff.py
tests/test_package.py

If the `--force` flag isn't given, catalog compile won't discard local changes (uncommitted, or unpushed changes, as well as local branches) in the global and tenant repo checkouts. Additionally, without `--force`, the catalog compilation won't discard uncommitted changes in tracked files in dependency repos. The `--force` flag has no effect in local mode.
Fixes #591

Add new command line flag `--force` for `catalog compile`

---

.editorconfig
commodore/dependency_mgmt/jsonnet_bundler.py
commodore/lib/kube-libsonnet/kube.libsonnet
commodore/lib/kube.libjsonnet
commodore/lib/kube.libsonnet
docs/modules/ROOT/pages/reference/kube-libjsonnet.adoc
docs/modules/ROOT/partials/nav-reference.adoc
pyproject.toml
tests/test_component_compile.py
tests/test_dependency_mgmt_jsonnet_bundler.py
tests/test_postprocess.py

Vendors `kube-libsonnet` and adds a depreciation notice that is currently not enabled by default.
Seems to be unused so I did not vendor it <https://github.com/search?q=%28%22utils.libsonnet%22+OR+%22utils.libjsonnet%22%29+AND+%28org%3Aprojectsyn+OR+org%3Aappuio+OR+org%3Avshn+%29&type=code>.
Only `vshn/cloudscale-metrics-collector` has added a [jsonnetfile.json](https://github.com/vshn/cloudscale-metrics-collector/blob/1fc786927d0cf4687ce3811fd1e2a6116bd82fa0/component/jsonnetfile.json#L7) with kube-libsonnet added. This was most likely by accident and I'll add a PR to remove it.
https://github.com/search?q=%22bitnami-labs%2Fkube-libsonnet%22+path%3A%2Fjsonnetfile%2F+AND+%28org%3Aprojectsyn+OR+org%3Aappuio+OR+org%3Avshn+%29&type=code
@simu and I decided that it is fine that …

Vendor `kube-libsonnet`

---

Dockerfile
README.md

We were still using Poetry 1.1.13 in the build stage of the Dockerfile. With the latest changes to Poetry (cf. #706 ), the `poetry.lock` format has changed in an incompatible way. Since we can't control the Poetry version used by Renovate, we simply update to the latest Poetry version in the Dockerfile.
See also https://python-poetry.org/blog/announcing-poetry-1.3.0/

Update Poetry to v1.3.1 in the Dockerfile

---

tox.ini

We can't currently upgrade to black 23, since there's a dependency conflict with kapitan 0.30. We should remove this once we upgrade to black 23 (#727), which will need to happen after the upgrade to kapitan 0.31 (#720).
We need to pin the black version in `tox.ini` since tox will otherwise install the latest v23 version, which brings some formatting changes compared to v22 (cf. the changelog in #727).

Pin black to 22.12.0

---

tox.ini

Switching test scheduling from `load` to `worksteal` cuts down test runtime on my 6 core/12 thread Ryzen 5 5600x from 51s wall 
time to 40s wall time for `make test_py3.11`:
With `-n auto --dist=worksteal`:
```
$ time make test_py3.11
poetry run tox -e py311
[ ... snipped ... ]
scheduling tests via WorkStealingScheduling
[ ... snipped ... ]
___________________________________________________________________________________ summary ___________________________________________________________________________________
py311: commands succeeded
congratulations :)
real	0m38.080s
user	1m6.428s
sys	0m13.098s
```
With `-n auto`:
```
$ time make test_py3.11
poetry run tox -e py311
[ ... snipped ... ]
scheduling tests via LoadScheduling
[ ... snipped ... ] …
```

Use pytest-xdist's new `worksteal` distribution mode

---

commodore/dependency_mgmt/component_library.py
docs/modules/ROOT/pages/reference/architecture.adoc
docs/modules/ROOT/pages/reference/component-deprecation.adoc
tests/test_dependency_mgmt_component_library.py

Commodore will verify that either the component who's prefix we're trying to take over isn't present in the cluster configuration (in this case the alias is just a regular alias) or that the component is deprecated, and has nominated us as their replacement component. Library prefixes of non-deprecated components, or deprecated components which don't specify a replacement can't be taken over.

Add support for taking over library prefix of deprecated components

---

renovate.json

If this works, we'll also setup auto-merge for minor and patch updates of development dependencies.
I've granted the renovate GitHub app user permissions to merge PRs without approval in the branch protection rules of the Commodore GitHub repo.

Configure Renovate auto-merge for lock file maintenance

---

commodore/helpers.py

This renders multiline YAML strings with literal newlines, for example a field `data` which has three lines of text which contain "foo", "bar", and "baz" respectively will now be rendered as follows by Kapitan.
```yaml
data: |
foo
bar
baz
```
This should improve readability of any manifests in the cluster catalog which contain large amounts of multi-line YAML strings, and should massively improve readability of catalog diffs for such manifests.
Follow-up to #720 

Switch to Kapitan's new `literal` multi-line YAML string style

---

commodore/cli/catalog.py
docs/modules/ROOT/pages/explanation/running-commodore.adoc
docs/modules/ROOT/pages/how-to/shell-completion.adoc
docs/modules/ROOT/partials/nav-howtos.adoc
tests/test_cli_catalog.py

This PR introduces auto-completion when compiling catalogs. This means
```
commodore catalog compile c-my-clu<TAB>
```
Will complete to
```
commodore catalog compile c-my-cluster
```
When lieutenant knows a cluster with id `c-my-cluster` (and the prefix `c-my-clu` is unique

Add auto-completion for catalog compilation

---

commodore/login.py

Until now, we unconditionally printed a message containing the OIDC login URL whenever Commodore needed to fetch a new OIDC token. The `webbrowser.open()` function returns a boolean which indicates whether the URL was opened successfully.
This commit checks the return value from `webbrowser.open()` and only prints a message if the URL couldn't be opened. This reduces the chances of this message messing up the terminal output when autocompletion is used (cf. #722), and reduces noise in general.
Follow-up for #722 

Only print a message when the OIDC login URL can't be opened automatically

---

commodore/cluster.py
commodore/component/compile.py
tests/test_component_compile.py

Until now, `commodore component compile` didn't correctly merge parameters provided in the instance's parameters key when compiling a multi-instance-enabled component in it's instantiated form (using the `--alias` flag of `component compile`).
The root cause for this error was that we didn't use the same logic to generate the Kapitan target in `component compile` and `catalog compile` until now. The PR refactors `render_target()` to pull out the instance logic into a separate function `generate_target()` which we can use for `component compile` as well.
The new `generate_target()` function expects a list of classes to use for field `classes` in the resulting Kapitan target, but contains all the logic to render the contents of field `parameters` which is identical for `component compile` …

Correctly merge instance parameters in `component compile`

---

commodore/catalog.py

This provides Git's stderr output when errors occur trying to push catalogs. Previously, only the exit code was returned, which usually is simply 1 and not very specific. 
The default branch in most Git hosting environments is called `main` now, but Commodore seems to expect the remote HEAD to be `master`. Trying a `commodore catalog compile --push` on a catalog repository with `main` as default branch will fail with "error: src refspec master does not match any...".
It would be cleverer to make Commodore read the default branch name from the remote repo and use that instead. But in the meantime, having more error output at least makes it possible to narrow down the cause of a push problem.
The stderr output seems to be truncated (by the GitRepo module?). I couldn't figure out how to get …

Provide more output for Git errors on push

---

tox.ini

We currently skip the following bandit checks to allow PRs to be merged
* B113: Requests call without timeout
* B603: subprocess call - check for execution of untrusted input.
* B607: Starting a process with a partial executable path
We'll address the lints in #758

Skip new bandit checks B113, B603, and B607

---

poetry.lock
pyproject.toml

We restrict boto3/botocore versions to reduce complexity of Poetry's dependency resolution significantly, cf.
https://github.com/orgs/python-poetry/discussions/8165#discussioncomment-6387378.
We put those dependencies first to constrain the Poetry dependency solver which processes dependencies in the order they're listed. Without these restrictions, the broad boto3 dependency specification in some of our dependencies (Kapitan, urllib) makes dependency resolution very slow.

Restrict boto3/botocore versions

---

commodore/refs.py
tests/test_refs.py

Until now, Commodore only parsed the first Kapitan secret reference in each string value. This can lead to compilation errors for cluster configurations which have fields whose values contain multiple secret references.
This commit updates the internal secret reference parsing in Commodore to find all non-overlapping secret references in strings instead of just the first one.
We also update the reference parsing test case to include an example string which contains two references.

Fix reference parsing for strings which contain multiple references

---

commodore/component/compile.py
commodore/package/compile.py
tests/test_component_compile.py

We manually generate a `cluster/params.yml` in `component compile` and `package compile`. This logic hasn't been updated to provide values for `${cluster:display_name}` and `${cluster:tenant_display_name}` in #311.
This PR updates `component compile` and `package compile` to provide dummy values for those variables and adjusts the component compilation tests to verify that these variables are provided.

Provide cluster and tenant display names in `component compile` and `package compile`

---

renovate.json

We don't need to get explicit PRs for boto3/botocore, since we only specify those packages as top-level dependencies to help Poetry's dependency resolver.
We add the packages to `ignoreDeps` in `renovate.json`. With this config, the two packages should still get updated once a week in the lockfile maintenance.
Follow-up for #810 

Disable explicit Renovate PRs for boto3/botocore

---

commodore/cluster.py
commodore/dependency_mgmt/__init__.py
tests/test_target.py

Uses `concurrent.futures.ThreadPoolExecutor` to fetch component and package dependencies in parallel.

Fetch component and package dependencies in parallel

---

commodore/dependency_mgmt/__init__.py
tests/test_dependency_mgmt.py

We need to collect the results from the iterator which is produced by `ThreadPool.map()` to ensure that exceptions raised in the worker threads are propagated to the main thread.
This PR collects the iterator by calling `list()` on it, which ensures that any exceptions raised in a worker thread are propagated to the main thread.
The PR also adds a test case which verifies that `fetch_components()` properly raises exceptions (e.g. when a requested component version doesn't exist).
Follow-up to #844 

Propagate exceptions raised while fetching dependencies

---

commodore/catalog.py
commodore/dependency_mgmt/jsonnet_bundler.py

We want to sort the components ascii-betically by name when generating the jsonnetfile.json and the catalog commit message. This ensures that the order remains the same across Commodore runs with parallel dependency fetching.
This also ensures that the behavior remains the same as it was before we introduced parallel dependency fetching, since the list of applications returned by Reclass is sorted ascii-betically.
Follow-up to #844

Fix component ordering in `jsonnetfile.json` and catalog commit message

---

commodore/cli/__init__.py

This is already the default on macOS, and doesn't break anything on Linux. We'll need this at the latest when we want to switch to gojsonnet, since that library doesn't work correctly with multiprocessing start method `fork`.
Additionally, we reduce the memory usage of Commodore by using start method `spawn` because the multiprocessing child processes are created with smaller initial memory working sets. However, this causes some execution time overhead because more data needs to be copied to the new processes. Locally, we measured an increase in runtime of approximately 4 seconds when using `spawn` compared to `fork`.

Use multiprocessing start method `spawn` by default

---

Dockerfile

`jb >= v0.6.2` improves the error handling when downloading packages.
See https://github.com/projectsyn/jsonnet-bundler/pull/4

Bump `jb` to `v0.6.2` in Dockerfile

---

.github/workflows/publish-pypi.yml

This should address the recent CI failures for the Test PyPI publishing errors, see e.g. https://github.com/projectsyn/commodore/actions/runs/6844060932/job/18607409336?pr=885
To be on the safe side, we also increase the connection timeout to prod PyPI to 60s.

Increase connection timeout for publishing package to PyPI

---

commodore/catalog.py
commodore/cli/__init__.py
commodore/cli/catalog.py
commodore/cluster.py
commodore/config.py
commodore/helpers.py
commodore/login.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_cluster.py
tests/test_commodore_libjsonnet.py
tests/test_login.py
tox.ini

The HTTP request timeout can be configured through a new command line flag (or associated environment variable). If the parameter isn't provided, we use a request timeout of 5 seconds.
Resolves #758 

Add explicit HTTP request timeouts

---

commodore/gitrepo/__init__.py
tests/conftest.py
tests/test_gitrepo.py

Until now, Commodore could fail to push the initial catalog for a cluster if the user's Git config sets `init.defaultBranch`. The
observed error is:
```
> Commiting changes...
> Pushing catalog to remote...
Error: Failed to push to the catalog repository: Git exited with status code 1
The error reported was:
stderr: 'error: src refspec master does not match any
error: failed to push some refs to 'ssh://<catalog repo>''
```
This error is caused because GitPython falls back to `init.defaultBranch` when creating the catalog repo unless `initial_branch` is specified.
However, since Commodore unconditionally falls back to trying to push `master` when no default branch can be identified in the remote repo (e.g. empty catalog repo), the push then fails because we're trying to push branch …

Ensure that cluster catalog is initialized with branch `master`

---

commodore/component/__init__.py

Mypy has started raising an error for generator functions (i.e. functions which use the `yield` keyword) which also contain a `return` statement.
From what I found in the docs, using yield makes the function return a generator in all cases. If execution hits a flow which doesn't encounter a yield statement (e.g. because the top-level condition is false) that generator will immediately raise a StopIteration exception.

Fix mypy error for spurious `return` in `Component.lib_files`

---

tests/test_component_template.py

This allows us to add new Cookiecutter context keys to the template without breaking the tests. The adjusted test just checks that all the known context keys are present, but doesn't fail if there are any additional context keys.
Discovered after https://github.com/projectsyn/commodore-component-template/pull/101 got merged.

Adjust component template tests to allow additional Cookiecutter context keys

---

commodore/cli/component.py
commodore/component/template.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_component_template.py

Follow-up for https://github.com/projectsyn/commodore-component-template/pull/101

Add options to configure dependency patch automerge behavior in components via `component new` and `component update`

---

commodore/cli/component.py
commodore/component/template.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_component_template.py

This PR adds command line flags and internal logic to allow users to configure the component template's patch automerging blocklist. We add command line flags that allow specifying regex patterns directly as well as flags that take a full dependency name and generate an anchored pattern from it.
Split out from #978.

Add command line flags for disabling automerging of patch updates for selected dependencies

---

commodore/cli/component.py
commodore/component/template.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_component_template.py

This PR introduces command line flags which allow users to configure an allowlist for automerging of minor updates for dependencies. We add command line flags that allow specifying regex patterns directly as well as flags that take a full dependency name and generate an anchored pattern from it.
Split out from #978 

 Add command line flags for configuring automerging of minor updates for selected dependencies

---

commodore/cli/component.py
commodore/component/template.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/test_component_template.py

Exposes the new cookiecutter arg for autorelease that was introduced in https://github.com/projectsyn/commodore-component-template/pull/110

Add CLI flag to control autorelease config in `component new` and `component update`

---

tests/test_component_template.py

We've updated the component template in https://github.com/projectsyn/commodore-component-template/pull/115. This PR updates the Commodore component template tests to match that change.

Fix tests to match that patch automerge now also automerges digest updates

---

.github/workflows/build-virtualenv-caches.yml
.github/workflows/coverage.yml
.github/workflows/publish-pypi.yml
.github/workflows/test.yml
README.md
docs/modules/ROOT/pages/explanation/running-commodore.adoc
poetry.lock
pyproject.toml
tox.ini
tox.mk

This is necessary so that we can update to Kapitan >= 0.33.x which drops support for Python 3.8 and 3.9.
This PR also removes test and benchmark targets for Python 3.8 and 3.9.
Since Python 3.8 will be EOL in a month (2024-10) and Python 3.9 would only be supported for a further year until 2025-10 (cf. https://devguide.python.org/versions/), we're not going to release this breaking change as a new major version.

Update minimum required Python to 3.10

---

Dockerfile
commodore/component/__init__.py
commodore/helpers.py
commodore/postprocess/builtin_filters.py
commodore/postprocess/jsonnet.py
poetry.lock
pyproject.toml
tests/conftest.py
tests/test_commodore_libjsonnet.py
tests/test_postprocess.py

We add go-jsonnet as a dependency, set `use_go_jsonnet=True` when calling `kapitan.targets.render_targets()` and replace our direct usages of jsonnet for rendering jsonnetfile.jsonnet for components and for postprocessing with go-jsonnet.
Additionally, we fix an oversight in the Jsonnet import callback used by the Commodore postprocessing where we should return a full path to the imported file but instead returned the filename only. With go-jsonnet this leads to an import loop for `lib/kube.libjsonnet` for the builtin `helm_namespace` filter. Interestingly, the same issue doesn't occur when using the same include in a Jsonnet postprocessing filter. Note that with C++ jsonnet we never had any issues with the previous import callback implementation. Additionally, note that Kapitan returns …

Use go-jsonnet in Commodore

---

docs/modules/ROOT/pages/explanation/running-commodore.adoc

The `gojsonnet` Python package requires a working Go compiler, since no wheels are published for that package. This commit updates the PyPI install instructions for Commodore with a prerequisite for a working Go compiler.
Follow-up for #1046 

Add a prerequisite for the Go compiler for go-jsonnet

---

commodore/cli/component.py
commodore/cli/options.py
commodore/cli/package.py
commodore/dependency_syncer.py
commodore/dependency_templater.py
docs/modules/ROOT/pages/reference/cli.adoc
tests/conftest.py
tests/test_cli_component.py
tests/test_cli_package.py
tests/test_dependency_sync.py

We make use of the native support for specifying a template version in Cruft to pass through a custom version in dependency update and sync.
We introduce flag `--template-version` for the component and package `update` and `sync` commands.
Resolves #618 

Add support for custom template versions for dependency update and sync

---

commodore/helpers.py
tests/test_helpers.py

We explicitly redo `POST` requests if we get a 301, 302, 307 or 308 status code for the first call. We don't validate that the redirect location has the same domain as the original request, since we already unconditionally follow redirects  with the bearer token for GET requests.
Note that this wouldn't be necessary if all Lieutenant APIs would redirect us with a 308 for POST requests.

Explicitly handle redirects when doing POST requests

---

commodore/compile.py
commodore/component/compile.py
commodore/config.py
tests/test_config.py

We need to check whether a component instance that sets a custom version supports per-instance versions by checking the instance's target's parameters. The bootstrap target ("cluster") doesn't have any instance-specific parameters, but since we do the validation after setting up all instance targets, we can use the instance's target to read `_metadata` of the alias's version to properly validate that both the base component and the alias are multi-version aware.
Additionally, because `component compile` doesn't have the regular bootstrap target (and generating it just for alias validation seems a bit overkill), we make the `bootstrap_target` key an optional parameter for `verify_component_aliases()` and set it to the component that's being compiled for `component compile` and fall back to …

Fix component multi-version verification

---

commodore/component/__init__.py
commodore/component/compile.py
tests/test_component.py

This simplifies a lot of the implementation for `Component` and only surfaces in a minor way in `component_compile` where we may need to create a fake `MultiDependency` if we compile a component outside a Git repo.
Split out from #1101 

Make the backing `MultiDependency` for `Component` non-optional

---

commodore/component/__init__.py
commodore/dependency_mgmt/__init__.py
tests/test_component.py
tests/test_dependency_mgmt.py

This ensures that `commodore catalog compile` doesn't silently discard local changes in a component instance worktree (the same as catalog compilation is already aborted when a component worktree with local changes is encountered).

Only discard changes in alias checkouts when catalog compilation called with `--force`

---

commodore/compile.py

We incorrectly used `gr.has_local_branches()` and
`gr.is_ahead_of_remote()` when checking whether the tenant repo has local branches or is ahead of the tracking branch.
NOTE: we don't need to fetch first when checking if we're ahead of the tracking branch, since the cases we want to cover are 1) forgot to push and 2) push failed but got overlooked before running `catalog compile`.

Correctly abort `catalog compile` for local changes in tenant repo

---

commodore/component/compile.py

We mount the component repo at `/<component-name>` in the Docker container when using `component compile` in the component template. In that case, the old code inferred `dependencies_dir` as `/` which isn't writable in the container environment.
This commit adjusts the implementation to use `config.inventory.dependencies_dir` which should always be writable. Since we don't actually use any functionality backed by `MultiDependency` in `component compile` it shouldn't matter whether we actually find the correct dependencies directory in all cases.
Fixes a bug introduced in #1102

Don't try to infer the dependencies directory in `component compile`

---

Dockerfile
README.md
docs/modules/ROOT/pages/explanation/running-commodore.adoc

Kapitan 0.34.5 has switched to the Python `filetype` library instead of the `python-magic` library. This removes the dependency on `libmagic1` for Kapitan and therefore also for Commodore, since we don't use filetype detection ourselves.
See also https://github.com/kapicorp/kapitan/pull/1304 and #1126

Remove libmagic1 from Docker image and from docs

---

commodore/dependency_templater.py
tests/test_component_template.py

Cruft's config file layout has changed slightly in a way which requires an adjustment for the dependency updater's custom diffing which can ignore diffs where only the template commit id in the `.cruft.json` changes.
This commit adjusts the custom diffing to cover the new case (while keeping the old cases), so we don't get useless template updates.
Additionally, we adjust the corresponding test to correctly mock the new `.cruft.json` layout.

Fix dependency updater custom `.cruft.json` diffing
