projectsyn/commodore

commodore/compile.py, commodore/target.py
Signed-off-by: Simon Rüegg <simon.ruegg@vshn.ch>
=> Move catalog URL to cluster dict

commodore/compile.py
Signed-off-by: Simon Rüegg <simon.ruegg@vshn.ch>
=> Use catalog repo url from dict

commodore/catalog.py, commodore/compile.py
Otherwise the refs will be cleaned up.
Signed-off-by: Simon Rüegg <simon.ruegg@vshn.ch>
=> Clean up catalog before writing refs

commodore/helpers.py, tests/test_helpers.py
The ApiError exception does not require any custom code.
=> Fix ApiError exception message handling

CHANGELOG.md
=> Prepare release v0.1.1

Pipfile.lock, renovate.json, requirements.txt, tools/Dockerfile.kapitan
Update the Kapitan docker image and various dependencies.
=> Update Various Dependencies

CHANGELOG.md, Pipfile.lock, requirements.txt, tools/Dockerfile.kapitan
Also update Kapitan again to include a hotfix: https://github.com/deepmind/kapitan/pull/516
=> Prepare Release v0.1.4

CHANGELOG.md
Signed-off-by: Simon Rüegg <simon@rueggs.ch>
=> Prepare release v0.1.6

.github/workflows/push.yml, .github/workflows/test.yml, Makefile, tools/Dockerfile.component_test
The linting image is meant as a runtime for linting Commodore
componentes.
=> Add Image for component testing

Pipfile.lock, requirements.txt
Should address the `lint_safety` failure for `httplib2`
=> Bulk update dependencies

Pipfile, Pipfile.lock
For some reason it was missing from the Pipfile.
=> Add missing dependency importlib-metadata

tests/test_dependency_mgmt.py, tests/test_git.py, tests/test_new-component.py, tests/test_target.py, tox.ini
So the tests don't depend on or affect the working dir.
Depends on https://github.com/projectsyn/commodore/pull/128
=> Run tests in temp dir and in parallel

CHANGELOG.md, commodore/cli.py, commodore/compile.py, commodore/helpers.py
Make use of the Kapitan library directly instead of spawning a subprocess.
=> Use Kapitan Python library

.github/ISSUE_TEMPLATE/01_bug_report.md, .github/ISSUE_TEMPLATE/02_feature_request.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
Apply the same GitHub issue and PR templates as are already applied to new components.
=> Add GitHub issue and PR templates

commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/test.yaml, commodore/component/template.py
=> Fix template typo

CHANGELOG.md, commodore/component-template/{{ cookiecutter.slug }}/.github/ISSUE_TEMPLATE/01_bug_report.md, commodore/component-template/{{ cookiecutter.slug }}/.github/ISSUE_TEMPLATE/02_feature_request.md
=> Add labels to issue templates

CHANGELOG.md
=> Prepare release v0.2.0

CHANGELOG.md, commodore/config.py
Always try to read the token from a file, not only in the constructor.
=> Fix read token from file

CHANGELOG.md, commodore/catalog.py, commodore/cli.py, commodore/config.py
First take on issue #69
Option --interactive introduced, let's the user choose if the push should be done or not.
=> Interactive push

CHANGELOG.md, commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/test.yaml, commodore/component-template/{{ cookiecutter.slug }}/.gitignore, commodore/component-template/{{ cookiecutter.slug }}/Makefile, commodore/component-template/{{ cookiecutter.slug }}/docs/modules/ROOT/pages/index.adoc, commodore/component-template/{{ cookiecutter.slug }}/docs/modules/ROOT/pages/references/parameters.adoc, commodore/component-template/{{ cookiecutter.slug }}/docs/modules/ROOT/partials/nav.adoc, commodore/component/template.py, tests/test_component_new.py
Extend docs setup in component template.
=> Extend Docs Template

CHANGELOG.md, tools/Dockerfile.kapitan
=> Prepare release v0.2.3

CHANGELOG.md, docs/modules/ROOT/pages/reference/architecture.adoc
=> Update default Vault values

CHANGELOG.md, commodore/dependency_mgmt.py
=> Ignore component version

CHANGELOG.md, commodore/component-template/{{ cookiecutter.slug }}/Makefile, commodore/component-template/{{ cookiecutter.slug }}/component/app.jsonnet
* Fix linting error in `component/app.jsonnet` for components which don't have a `-` in their name.
* Add `--pad-arrays` option to jsonnetfmt arguments in component template Makefile
=> Update component template

.gitignore, CHANGELOG.md, Dockerfile, README.md, commodore/compile.py, commodore/component-template/{{ cookiecutter.slug }}/.gitignore, commodore/component/compile.py, commodore/dependency_mgmt.py, commodore/helpers.py, docs/modules/ROOT/pages/dependencies.adoc, docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/partials/nav-explanation.adoc
=> Manage dependencies using jsonnet-bundler

CHANGELOG.md
This change fixes some links within the change log.
=> Fix GitHub links in CHANGELOG

CHANGELOG.md, commodore/cluster.py
=> Make all facts available as `parameters.facts`

CHANGELOG.md, commodore/component/template.py, tests/test_component.py
=> Commit .editorconfig in initial commit for component repo

CHANGELOG.md
=> Prepare release v0.3.0

CHANGELOG.md, commodore/dependency_mgmt.py, tests/test_dependency_mgmt.py
To make sure the lock file is updated.
=> Clear Jsonnet Lock File

CHANGELOG.md, commodore/lib/commodore.libjsonnet
=> Merge arrays in Jsonnet helper

CODE_OF_CONDUCT.md, CONTRIBUTING.md, commodore/component-template/{{ cookiecutter.slug }}/CODE_OF_CONDUCT.md, commodore/component-template/{{ cookiecutter.slug }}/CONTRIBUTING.md
=> Fix link in Contribution Guide

docs/modules/ROOT/pages/running-commodore.adoc
=> Explain how to do SSH-agent forwarding on macOS

commodore/component/__init__.py, commodore/component/compile.py, commodore/component/template.py, commodore/config.py, commodore/dependency_mgmt.py, tests/test_dependency_mgmt.py, tests/test_postprocess.py
#230 starts to get too big to handle. This one got extracted from there.
=> Move Component class to component package

commodore/component/compile.py, commodore/dependency_mgmt.py, commodore/helpers.py, tests/test_dependency_mgmt.py
#230 starts to get too big to handle. This one got extracted from there.
=> Pass source as single argument to `relsymlink()`

commodore/component/__init__.py, commodore/component/compile.py, commodore/component/template.py, commodore/config.py, commodore/dependency_mgmt.py, tests/test_dependency_mgmt.py, tests/test_postprocess.py
This is another break out of #230.
=> Make Component a plain Python object

CHANGELOG.md, commodore/dependency_mgmt.py, commodore/helpers.py, tests/test_dependency_mgmt.py
=> Drop check for "Old-style" components

commodore/component/__init__.py, commodore/component/compile.py, commodore/component/template.py, commodore/dependency_mgmt.py, tests/test_dependency_mgmt.py, tests/test_postprocess.py
This is another break out of #230.
=> Refactor git repo handling into Component

Makefile, commodore/component/compile.py, tests/test_component_compile.py, tox.mk
Additionally fix small things in Makefile.
=> Remove "standalone" in component compile output path

commodore/component/__init__.py, commodore/component/compile.py, commodore/dependency_mgmt.py, commodore/postprocess/__init__.py, tests/test_component_compile.py
#230 starts to get too big to handle. This one got extracted from there.
=> More specific properties to Component::target_directory

commodore/cluster.py, commodore/compile.py, commodore/component/compile.py, commodore/component/template.py, commodore/config.py, commodore/dependency_mgmt.py, commodore/helpers.py, commodore/inventory.py, tests/test_component.py, tests/test_dependency_mgmt.py, tests/test_inventory.py, tests/test_target.py
This is another break out of #230. With this refactoring, everything related to inventory paths got pulled together into an `Inventory` class.
=> Introduce Inventory class

CHANGELOG.md, commodore/compile.py, commodore/component/compile.py, commodore/dependency_mgmt.py, tests/test_dependency_mgmt.py
=> Pull essential libraries with Jsonnet Bundler

CHANGELOG.md, commodore/cluster.py, commodore/compile.py, commodore/component/template.py, commodore/config.py, commodore/dependency_mgmt.py, commodore/git.py, docs/modules/ROOT/pages/reference/architecture.adoc, tests/test_config.py, tests/test_dependency_mgmt.py, tests/test_target.py
=> Add support for component instantiation

CHANGELOG.md, commodore/catalog.py, commodore/cli.py, commodore/cluster.py, commodore/compile.py, commodore/component/__init__.py, commodore/component/compile.py, commodore/component/template.py, commodore/config.py, commodore/dependency_mgmt.py, commodore/helpers.py, commodore/inventory.py, commodore/postprocess/__init__.py, commodore/postprocess/builtin_filters.py, commodore/postprocess/jsonnet.py, commodore/refs.py, docs/modules/ROOT/pages/reference/cli.adoc, tests/test_catalog.py, tests/test_cluster.py, tests/test_component.py, tests/test_component_compile.py, tests/test_component_template.py, tests/test_config.py, tests/test_dependency_mgmt.py, tests/test_inventory.py, tests/test_postprocess.py, tests/test_target.py, tox.ini
=> Implement configurable working directory

.github/workflows/test.yml, commodore/component/__init__.py, poetry.lock, pyproject.toml, tests/bench_component.py, tests/test_component.py, tests/test_dependency_mgmt.py, tox.ini, tox.mk
This PR
* Adds infrastructure to run benchmarks and tests
* Adds tests for `Component.checkout`
* Reimplements `Component.checkout` to be roughly twice as fast as the old implementation.
=> Component checkout improvements

CHANGELOG.md, commodore/cli.py, commodore/cluster.py, commodore/config.py, commodore/dependency_mgmt.py, docs/modules/ROOT/pages/reference/cli.adoc, tests/test_catalog.py, tests/test_cluster.py, tests/test_config.py, tests/test_dependency_mgmt.py, tests/test_target.py
=> Drop COMMODORE_GLOBAL_GIT_BASE

CHANGELOG.md, commodore/helpers.py, tests/test_helpers.py
Resolves #218
This one needs #250 to work properly.
=> Keep dependencies dir on clean up

CHANGELOG.md, commodore/cli.py
=> Allow to configure working dir by env

commodore/__init__.py
=> set project URL to GitHub

CHANGELOG.md, commodore/cluster.py, tests/test_cluster.py
=> Ensure tenant config uses the correct revision

README.md, docs/modules/ROOT/pages/running-commodore.adoc
It's deprecated and not used anymore.
Implemented in #247
=> Remove references to global Git base

.github/workflows/push-kapitan.yml
* Adjust version extraction from Dockerfile
* Directly use variables in build step
=> Fix GitHub action for building Kapitan Docker image

README.md, docs/modules/ROOT/pages/running-commodore.adoc, poetry.lock, tools/Dockerfile.kapitan
=> Bump dependencies

CHANGELOG.md, docs/modules/ROOT/pages/reference/architecture.adoc
* Fixes #71 - via #223 and Kapitan update to v0.29.4
* Fixes #233 - via Kapitan update to v0.29.2+
=> Prepare release v0.4.1

CHANGELOG.md, commodore/component-template/{{ cookiecutter.slug }}/Makefile
As mentioned in https://github.com/projectsyn/component-thanos/pull/1
=> Update template to ignore `vendor/` from linting

CHANGELOG.md, tox.ini
=> Update pytest options to remove warnings

CHANGELOG.md, docs/modules/ROOT/pages/reference/deprecation-notices.adoc, docs/modules/ROOT/pages/reference/deprecation-policy.adoc
=> Prepare release v0.5.0

docs/modules/ROOT/pages/reference/deprecation-notices.adoc
=> Add deprecation notice for parameters which were deprecated in v0.3.0

.github/workflows/test.yml, CHANGELOG.md, tox.mk
=> Add Python 3.9 to test matrix

CHANGELOG.md, docs/modules/ROOT/pages/reference/deprecation-notices.adoc
=> Prepare release v0.6.0

CHANGELOG.md, docs/modules/ROOT/pages/local-mode.adoc
=> Small improvements in local mode documentation

commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/release.yaml
Fix whitespace error from yamllint in component template
=> Fix whitespace error from yamllint in component template

docs/modules/ROOT/pages/reference/component-deprecation.adoc
=> Fix typo in examples

poetry.lock
This includes the update to Kapitan v0.29.5.
Fixes #323.
=> Bulk update Python dependencies

tools/Dockerfile.kapitan
=> Bump Kapitan for ArgoCD to v0.29.5

.dockerignore, .github/workflows/publish-pypi.yml, Dockerfile, Makefile, README.md, commodore/__init__.py, commodore/cli.py, commodore/copy_helm_bindings.py, pyproject.toml
Create and publish a pypi package.
It contains pre-compiled helm bindings. They need to be copied to the right place with `copy_helm_bindings` after the pip install.
Package is only build on master and pushed on tags.
[ ] Pushing to pypi needs a token in the github repo.
=> Create a pypi package and publish it

commodore/component-template/{{ cookiecutter.slug }}/.sync.yml, commodore/component-template/{{ cookiecutter.slug }}/Makefile, commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk, commodore/component-template/{{ cookiecutter.slug }}/tests/defaults.yml
This PR makes new component ModuleSync-ready by adding config overrides in `.sync.yml`.
=> Add ModuleSync support in component template

tests/test_catalog_compile.py
=> Use fixed globalGitRepoRevision for integration test

commodore/postprocess/__init__.py, commodore/postprocess/builtin_filters.py, commodore/postprocess/jsonnet.py
This commit makes use of the information provided in Component objects to do the postprocessing filter lookup for filters of type `jsonnet`.
This fixes the "Jsonnet filter definition does not exist" error which previously popped up when running trying to compile components with postprocessing filters with `commodore component compile .`.
=> Fix postprocessing filter lookup

tests/test_postprocess.py
* Use `pytest.mark.parametrize` to reduce amount of duplicated test code
* Add tests for Jsonnet postprocessing filter
=> Refactor postprocessing tests

commodore/component/__init__.py
=> Fix `Component.filters_file` to use `target_directory`

.github/workflows/publish-pypi.yml, .github/workflows/test.yml, Makefile, README.md, pyproject.toml
* Remove no longer required steps to build Helm bindings in GitHub action
* Build package on PRs
* Publish package to test.pypi.org on PRs and latest builds
* Publish package to pypi.org on tags
* Correctly specify supported Python versions in README and pyproject.toml as 3.7, 3.8 and 3.9
=> Fix and improve PyPI build

commodore/cli.py, commodore/component-template/cookiecutter.json, commodore/component-template/hooks/post_gen_project.py, commodore/component-template/{{ cookiecutter.slug }}/.editorconfig, commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/test.yaml, commodore/component-template/{{ cookiecutter.slug }}/.gitignore, commodore/component-template/{{ cookiecutter.slug }}/.sync.yml, commodore/component-template/{{ cookiecutter.slug }}/Makefile, commodore/component/template.py, docs/modules/ROOT/pages/reference/cli.adoc, tests/test_component_template.py
See https://github.com/projectsyn/modulesync-control/pull/22 as to why golden tests can be a good idea.
=> Add golden and matrix tests to component template

.dockerignore, Dockerfile, tools/install-jb.sh
=> Allow ARM Docker build

docs/modules/ROOT/pages/reference/parameters.adoc
=> Fix typos in dynamic facts example

commodore/component-template/{{ cookiecutter.slug }}/.github/PULL_REQUEST_TEMPLATE.md, commodore/component-template/{{ cookiecutter.slug }}/Makefile
See
* https://github.com/projectsyn/modulesync-control/pull/49
* https://github.com/projectsyn/modulesync-control/pull/50
=> Sync component template from modulesync-control

commodore/dependency_mgmt.py, docs/modules/ROOT/pages/reference/deprecation-notices.adoc, tests/test_catalog_compile.py, tests/test_dependency_mgmt.py
=> Add deprecation notice for component specifications without explicit version

commodore/cli.py, commodore/inventory/parameters.py, commodore/inventory/render.py, docs/modules/ROOT/pages/reference/commands.adoc, tests/test_inventory_parameters.py, tests/test_inventory_render.py
Will be used in https://github.com/projectsyn/commodore-renovate/pull/5
=> Add support for tenant repo in `commodore inventory components`

poetry.lock
=> Update Python dependencies

Dockerfile
=> Update Docker base image to `python:3.9.10-slim-bullseye`

.github/workflows/publish-pypi.yml
=> Cache virtualenv in GitHub action which publishes the package on PyPI

.github/workflows/build-virtualenv-caches.yml, .github/workflows/test.yml, tox.ini, tox.mk
=> Add GitHub action to build virtualenv caches on master branch 

poetry.lock, pyproject.toml, tests/test_catalog_compile.py
=> Address black format linting errors

.github/workflows/build-virtualenv-caches.yml, .github/workflows/test.yml, tox.mk
See commits for individual changes
=> Add virtualenv caching for linting GitHub actions and rebuild base cache weekly

Makefile, commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
=> Updated antora-preview image

tox.mk
=> Fix typo in `testenv_py3.10` make target

commodore/cli.py, commodore/config.py, commodore/login.py, tests/test_config.py
=> Auto-login when trying to authenticate without token

.codeclimate.yml, .github/workflows/build-virtualenv-caches.yml, .github/workflows/test.yml, Makefile, poetry.lock, pyproject.toml, tests/test_commodore_libjsonnet.py
Setup codeclimate maintainability and code coverage. We tune the maintainability checks in this PR to avoid having over 50 issues right from the start. We can always lower thresholds in the future. You can run the maintainability analysis locally with
```
docker run  -it --rm --env CODECLIMATE_CODE="$PWD" \
--volume "$PWD":/code \
--volume /var/run/docker.sock:/var/run/docker.sock \
--volume /tmp/cc:/tmp/cc \
codeclimate/codeclimate analyze
```
=> Setup codeclimate checks and code coverage

commodore/component/compile.py
=> Print deprecation notices in `component compile`

commodore/component/compile.py, commodore/dependency_mgmt.py, docs/modules/ROOT/pages/reference/concepts.adoc, docs/modules/ROOT/pages/reference/deprecation-notices.adoc, tests/test_component_compile.py, tests/test_dependency_mgmt.py
First part of implementing #417
=> Register deprecation notices for invalid component library names

commodore/compile.py, commodore/dependency_mgmt.py, docs/modules/ROOT/pages/reference/architecture.adoc, tests/test_dependency_mgmt.py
=> Raise error for component version overrides without an URL

commodore/cli.py, commodore/component/compile.py
=> Refactor `component_compile()`

commodore/dependency_mgmt.py
We move extracting components from the `applications` array from `_discover_components()` to a separate function reduce the complexity of `_discover_components()`.
=> Refactor `_discover_components()` to reduce complexity

tests/test_catalog.py
=> Add test for `update_catalog()`

tests/test_catalog.py, tests/test_dependency_mgmt.py
Follow-up for #440, #447, and #450
=> Fix tests which validate expected exceptions

commodore/config.py, docs/modules/ROOT/pages/reference/deprecation-notices.adoc, tests/test_component_compile.py, tests/test_config.py
=> Remove support for multi-instance advertisement in top-level parameter `multi_instance`

commodore/component/compile.py, commodore/dependency_mgmt.py, docs/modules/ROOT/pages/reference/deprecation-notices.adoc, tests/test_dependency_mgmt.py
=> Raise error for component library name with invalid prefix

poetry.lock, pyproject.toml
Python 3.10 needs a `pytest` which is newer than 5.4.
=> Update dev dependencies

tests/test_postprocess.py
=> Add more tests for the Jsonnet postprocessing filter runner

Makefile, tests/test_catalog_compile.py
=> Add integration test for `catalog compile --local`

commodore/cli.py, commodore/login.py, docs/modules/ROOT/pages/reference/cli.adoc, docs/modules/ROOT/pages/reference/commands.adoc, tests/test_cli.py, tests/test_cli_functions.py, tests/test_login.py
=> Add command `commodore fetch-token` to print API token to stdout

pyproject.toml
=> Pin `tox` and `autopep8` versions in `pyproject.toml`

commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/release.yaml
See also https://github.com/projectsyn/modulesync-control/pull/75
=> Bump release-changelog-builder-action to v3 in component template

README.md
This aligns the README with the rest of Project Syn.
=> Reformat README to consistently follow sentence-per-line style

commodore/cli.py
=> Configure CLI to also accept `-h` to print help text

commodore/cli.py, commodore/compile.py, commodore/package/compile.py, docs/modules/ROOT/pages/reference/cli.adoc, docs/modules/ROOT/pages/reference/commands.adoc, tests/test_cli.py, tests/test_package_compile.py
=> Add command `commodore package compile`

commodore/cli.py, commodore/component/template.py, commodore/dependency_templater.py, commodore/package/template.py, docs/modules/ROOT/pages/reference/cli.adoc, docs/modules/ROOT/pages/reference/commands.adoc, poetry.lock, pyproject.toml, tests/test_cli.py, tests/test_package_template.py
=> Add command `package new`

poetry.lock, pyproject.toml
This way we should get "real" Renovate PRs for dependency updates instead of the weekly generic "Lock file maintenance" PRs.
=> Remove all version range specifications for dependencies in `pyproject.toml`

commodore/component-template/{{ cookiecutter.slug }}/.sync.yml, commodore/component-template/{{ cookiecutter.slug }}/README.md, tests/test_component_template.py
Related to https://github.com/projectsyn/modulesync-control/pull/80
=> Add link to rendered documentation in component template README

docs/modules/ROOT/pages/tutorial/package.adoc, docs/modules/ROOT/partials/nav-tutorials.adoc
=> Add short tutorial on how to write and use commodore packages

commodore/package/sync.py, tests/test_package_sync.py
Previously we returned `None` from `ensure_pr()` when doing a dry-run sync or on an error. However, we printed the regular success message on None returns. This creates a output message along the lines of "PR for package organization/package successfully None".
This commit refactors how we generate and print the final message for each package. Instead of returning "created", "updated" or None from `ensure_pr()`, we return the preformatted message which can just be printed in `sync_packages()`.
Follow-up for #572
=> Fix console output for `package sync`

docs/modules/ROOT/pages/explanation/running-commodore.adoc
=> Add a note about required dev packages for building Commodore dependencies

docs/modules/ROOT/pages/tutorial/package.adoc
=> Fix config package path in package tutorial

commodore/component/__init__.py, commodore/gitrepo.py, commodore/multi_dependency.py, commodore/package/__init__.py, tests/conftest.py
=> Correctly propagate Git author information when managing worktrees

docs/modules/ROOT/pages/tutorial/package.adoc
=> Add warning regarding "class not found" messages when using packages

commodore/gitrepo.py
We fall back to `Commodore <commodore@syn.tools>` as the user info when we fail to read any user information from the Git configuration.
Follow-up to #598, #602, #603
=> Handle `KeyError` when reading Git user from config

commodore/dependency_templater.py, tests/test_component_template.py
We read the cookiecutter args from the dependency's `.cruft.json` if it exists. This allows us to correctly update dependencies which use cookiecutter args which Commodore doesn't know about.
=> Read cookiecutter args from `.cruft.json` in Templater

commodore/component/template.py, commodore/dependency_templater.py, tests/test_component_template.py
Check the component implementation to determine whether the component has postprocessing filters and a component library if flags `add_pp` and `add_lib` aren't present in `.cruft.json`. This allows us to migrate to Cruft from modulesync easier as we don't have enough info in modulesync to set these flags.
=> Add fallback logic for component template `add_pp` and `add_lib` cookiecutter args

.dockerignore, Dockerfile, docs/modules/ROOT/pages/explanation/running-commodore.adoc, renovate.json
Adds `kustomize` as a usable tool to the Commodore Docker image.
Script taken from upstream.
I'll write up a documentation how to use it at a later point after some experience.
=> Add `kustomize` to container image

commodore/cli.py, commodore/dependency_syncer.py, commodore/dependency_templater.py, docs/modules/ROOT/pages/reference/cli.adoc, tests/test_component_template.py, tests/test_dependency_sync.py
=> Add option to skip committing changes for `component update`/`package update`

tests/test_component_template.py
We've removed the `.sync.yml` template from the component template in https://github.com/projectsyn/commodore-component-template/pull/14. Since merging that PR, the Commodore tests which verify that newly created components have a `.sync.yml` have been failing.
This commit updates all tests which verify the template metadata in components to check `.cruft.json` instead of `.sync.yml`.
This PR is labelled `ignore` since it doesn't need to appear in the Commodore release notes.
=> Update component template tests to verify `.cruft.json` instead of `.sync.yml`

Dockerfile
Switch to the currently recommended install script for Poetry in the Dockerfile. See also https://python-poetry.org/docs/#installing-with-the-official-installer
=> Update poetry install URL in Dockerfile

commodore/gitrepo.py, tests/test_gitrepo.py
We change the implementation of `stage_all()` to use the results of `git.Repo.untracked_files` and `git.index.diff(None)` to stage all changes instead of `Repo.index.add('*')`.
This change ensures that we respect the contents of `.gitignore` when staging changes with `stage_all()` as both `git.Repo.untracked_files` calls out to `git status` and therefore takes into account `.gitignore`, and `git.index.diff(None)` will never consider untracked files and thus won't ever cause untracked ignored files to be staged.
Fixes #626
=> Modify `GitRepo.stage_all()` to respect `.gitignore`

commodore/gitrepo.py, tests/test_gitrepo.py
=> Add support for custom ignore patterns in `GitRepo.stage_all()`

docs/modules/ROOT/pages/explanation/local-mode.adoc, docs/modules/ROOT/pages/how-to/local-mode-component.adoc, docs/modules/ROOT/partials/nav-howtos.adoc
Move how-to bits from the explanation page into a how-to page.
Part of #590 
=> Improve local mode documentation

.github/workflows/build-virtualenv-caches.yml, .github/workflows/test.yml, docs/modules/ROOT/pages/explanation/running-commodore.adoc, poetry.lock, pyproject.toml, tox.ini, tox.mk
=> Add Python 3.11 as supported version

README.md
=> Update supported Python versions in README.md

commodore/catalog.py, commodore/cli/catalog.py, commodore/config.py, commodore/helpers.py, docs/modules/ROOT/pages/reference/cli.adoc, tests/test_catalog.py, tests/test_helpers.py
=> Fix list indentation if using post-process filters

docs/modules/ROOT/pages/explanation/running-commodore.adoc
After investing quite some time into getting commodore working locally, I've written down the pitfals.
=> Add some additional notes for commodore installation

README.md
=> Add libmagic to system requirements

Makefile, docs/modules/ROOT/pages/explanation/running-commodore.adoc
Additionally, update the documentation container images to their latest versions
=> Fix documentation container image locations

.github/workflows/coverage.yml, .github/workflows/test.yml, Dockerfile, README.md, docs/modules/ROOT/pages/explanation/running-commodore.adoc, tools/install-jb.sh
Switches to a `jsonnet-bundler` fork with deterministic dependency resolution and parallel fetchching of the dependencies
=> Use the projectsyn fork of jsonnet-bundler

commodore/cli/component.py
=> Deduplicate options for `component new` and `component update`

commodore/inventory/parameters.py, commodore/inventory/render.py, tests/test_inventory_render.py
=> Refactor `commodore inventory` to use reclass-rs

Dockerfile, renovate.json
=> Configure Renovate regex manager for Go toolchain in Dockerfile

renovate.json
* Configure Renovate to create separate Python patch/minor version update PRs for Dockerfile
* Disable Renovate for Python version in `pyproject.toml`
=> Adjust Renovate configuration for Python versions

commodore/dependency_mgmt/__init__.py, tests/test_dependency_mgmt.py
=> Wrap `gitrepo.RefError` in a nice error message for dependency fetching

commodore/component/compile.py
Update `ArgoApp()` to have the newly introduced optional `base` parameter.
See https://github.com/projectsyn/component-argocd/pull/226 for more context.
=> Update `component compile` mock `argocd.libjsonnet`

commodore/cluster.py, commodore/helpers.py, docs/modules/ROOT/pages/reference/parameters.adoc, tests/test_helpers.py
=> Make Commodore Python 3 executable available as Reclass variable `_python3`

Dockerfile
=> Docker: Ensure Go is available to build jsonnet dependencies on non-x86 architectures.

commodore/dependency_syncer.py, tests/test_dependency_sync.py
We simplify the pausing logic in the dependency sync `_maybe_pause()` helper to pause after we've created exactly `pr_batch_size` PRs instead of every time when `update_count > 0 and update_count % pr_batch_size == 0`.
Instead of keeping the `update_count` counter going up, we reset it after each pause to avoid excessive amounts of pauses when updating a subset of dependencies, but more than `pr_batch_size` overall.
=> Fix pausing logic in dependency sync main loop
